(function () {
  const threads = [
    { space:'Vragen & twijfel', icon:'?', title:'Wanneer is twijfel gezond — en wanneer wordt het uitstel?', intro:'Hoe vinden we het verschil tussen kritisch blijven en nooit meer tot een besluit komen?', body:'Twijfel kan ons beschermen tegen te snelle conclusies. Tegelijk kunnen we ons ook achter twijfel verschuilen wanneer een beslissing moeilijk voelt.\n\nWelke signalen helpen jou om dat onderscheid te maken? En welke rol spelen bronnen, ervaring en vertrouwen daarin?', source:'manifest.html' },
    { space:'Ervaringen', icon:'≈', title:'Wat helpt een lichaam opnieuw veiligheid herkennen?', intro:'Een gesprek over herstel zonder te doen alsof één aanpak voor iedereen werkt.', body:'In verhalen over trauma gaat het vaak over begrijpen wat er gebeurd is. Maar herstel wordt ook lichamelijk ervaren: rust, verbinding, voorspelbaarheid of opnieuw durven voelen.\n\nWelke kleine dingen hebben jou geholpen, en hoe delen we ervaringen zonder ze als universeel advies voor te stellen?', source:'onderwerpen/trauma.html' },
    { space:'Bronnen gezocht', icon:'↗', title:'Welke bronnen leggen neuroplasticiteit helder én eerlijk uit?', intro:'Gezocht: toegankelijke bronnen die mogelijkheden tonen zonder wonderclaims.', body:'Neuroplasticiteit wordt soms voorgesteld alsof we ons brein onbeperkt kunnen herprogrammeren. Andere uitleg is dan weer zo technisch dat bijna niemand ze begrijpt.\n\nWelke onderzoekers, boeken of publieke bronnen leggen zowel de mogelijkheden als de grenzen goed uit?', source:'onderwerpen/neuroplasticiteit.html' },
    { space:'Vragen & twijfel', icon:'☾', title:'Is bewustzijn volledig te verklaren vanuit het brein?', intro:'Waar eindigt wat we onderzocht hebben en waar begint de filosofische vraag?', body:'Hersenonderzoek laat sterke verbanden zien tussen hersenactiviteit en bewuste ervaring. Toch blijft de vraag waarom een ervaring ook van binnenuit voelt zoals ze voelt.\n\nWelke delen kunnen we wetenschappelijk bespreken, welke zijn filosofisch en wanneer wordt een idee speculatief?', source:'onderwerpen.html?gebied=Bewustzijn+%26+metafysica' },
    { space:'Projectideeën', icon:'✦', title:'Hoe zou een werkelijk veilige plek voor kinderen eruitzien?', intro:'Van kritiek op systemen naar een concreet en toetsbaar alternatief.', body:'Het denkstuk “Een kind is geen dossier” eindigt met het beeld van een plek waar gemeenschap en veiligheid centraal staan.\n\nWelke mensen, regels, controles en dagelijkse gewoonten zijn nodig om zo’n idee niet alleen warm, maar ook werkelijk veilig te maken?', source:'denk-box02.html' },
    { space:'Over het platform', icon:'◉', title:'Hoe maken we zelfonderzoek veilig zonder elkaar te diagnosticeren?', intro:'Welke ontwerpregels helpen om herkenning en steun niet te verwarren met behandeling?', body:'Persoonlijke verhalen en oefeningen kunnen veel herkenning oproepen. Tegelijk kent niemand via een scherm het volledige leven van een ander.\n\nWelke forumregels en functies zouden jou helpen om steun te geven zonder etiketten, diagnoses of ongewenst advies?', source:'manifest.html' }
  ];
  const list=document.querySelector('[data-thread-list]'); if(!list)return;
  const query=document.querySelector('[data-forum-query]'); const spacesRoot=document.querySelector('[data-forum-spaces]'); const count=document.querySelector('[data-forum-count]'); const heading=document.querySelector('[data-forum-heading]'); const empty=document.querySelector('[data-forum-empty]');
  const shell=document.querySelector('.forum-shell'); const reader=document.querySelector('[data-thread-reader]'); const composer=document.querySelector('[data-forum-composer]'); const preview=document.querySelector('[data-thread-preview]'); const form=document.querySelector('[data-thread-form]');
  let activeSpace='Alles';
  const spaces=['Alles',...new Set(threads.map(thread=>thread.space))];
  const normalize=value=>String(value||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
  function renderSpaces(){ spacesRoot.replaceChildren(...spaces.map(space=>{const button=document.createElement('button');button.type='button';button.className='space-button';button.setAttribute('aria-pressed',String(space===activeSpace));const label=document.createElement('span');label.textContent=space;const total=document.createElement('span');total.textContent=space==='Alles'?threads.length:threads.filter(thread=>thread.space===space).length;button.append(label,total);button.addEventListener('click',()=>{activeSpace=space;render();});return button;})); }
  function openThread(thread){ document.querySelector('[data-reader-space]').textContent=thread.space;document.querySelector('[data-reader-title]').textContent=thread.title;document.querySelector('[data-reader-intro]').textContent=thread.intro;document.querySelector('[data-reader-body]').textContent=thread.body;const source=document.querySelector('[data-reader-source]');source.href=thread.source;source.textContent=thread.source;hidePanels();reader.hidden=false;reader.focus(); }
  function threadCard(thread){const button=document.createElement('button');button.type='button';button.className='thread-card';const icon=document.createElement('span');icon.className='thread-card__icon';icon.textContent=thread.icon;const content=document.createElement('span');const labels=document.createElement('span');labels.className='thread-card__labels';labels.textContent=`${thread.space} · Voorbeeldgesprek`;const title=document.createElement('h3');title.textContent=thread.title;const intro=document.createElement('p');intro.textContent=thread.intro;content.append(labels,title,intro);const arrow=document.createElement('span');arrow.className='thread-card__arrow';arrow.textContent='→';arrow.setAttribute('aria-hidden','true');button.append(icon,content,arrow);button.addEventListener('click',()=>openThread(thread));return button;}
  function render(){const value=query.value.trim();const results=threads.filter(thread=>(activeSpace==='Alles'||thread.space===activeSpace)&&normalize([thread.title,thread.intro,thread.body,thread.space].join(' ')).includes(normalize(value)));list.replaceChildren(...results.map(threadCard));list.hidden=!results.length;empty.hidden=!!results.length;count.textContent=`${results.length} ${results.length===1?'voorbeeld':'voorbeelden'}`;heading.textContent=activeSpace==='Alles'?'Alle voorbeeldgesprekken':activeSpace;renderSpaces();}
  function hidePanels(){shell.hidden=true;reader.hidden=true;composer.hidden=true;preview.hidden=true;}
  function showShell(){hidePanels();shell.hidden=false;document.querySelector('.forum-toolbar').scrollIntoView({behavior:'smooth',block:'start'});}
  function showComposer(){hidePanels();composer.hidden=false;composer.focus();}
  document.querySelector('[data-open-composer]').addEventListener('click',showComposer);document.querySelector('[data-empty-compose]').addEventListener('click',showComposer);document.querySelector('[data-close-thread]').addEventListener('click',showShell);document.querySelectorAll('[data-close-composer]').forEach(button=>button.addEventListener('click',showShell));document.querySelector('[data-reply-prototype]').addEventListener('click',showComposer);
  query.addEventListener('input',render);
  const title=form.elements.title;const body=form.elements.body;const words=value=>value.trim()?value.trim().split(/\s+/).length:0;
  function counters(){document.querySelector('[data-title-count]').textContent=`${title.value.length}/100`;document.querySelector('[data-body-count]').textContent=`${words(body.value)} woorden`;}
  title.addEventListener('input',counters);body.addEventListener('input',counters);counters();
  function error(field,message){field.setAttribute('aria-invalid',message?'true':'false');document.getElementById(`${field.id}-error`).textContent=message;return !message;}
  function validate(){let valid=true;valid=error(form.elements.space,form.elements.space.value?'':'Kies een gespreksruimte.')&&valid;valid=error(title,title.value.trim().length>=10?'':'Gebruik minstens 10 tekens voor je titel.')&&valid;valid=error(body,words(body.value)>=40?'':'Geef minstens 40 woorden uitleg en context.')&&valid;let sourceError='';if(form.elements.source.value){try{if(new URL(form.elements.source.value).protocol!=='https:')sourceError='Gebruik een volledige https-link.';}catch{sourceError='Gebruik een volledige https-link.';}}valid=error(form.elements.source,sourceError)&&valid;const checks=[form.elements.respect,form.elements.privacy];const errorRoots=[document.querySelector('[data-respect-error]'),document.querySelector('[data-privacy-error]')];checks.forEach((check,index)=>{errorRoots[index].textContent=check.checked?'':'Deze bevestiging is nodig.';if(!check.checked)valid=false;});if(form.elements.website.value)valid=false;return valid;}
  function showPreview(){document.querySelector('[data-preview-space]').textContent=form.elements.space.value;document.querySelector('[data-preview-thread-title]').textContent=title.value.trim();document.querySelector('[data-preview-author]').textContent=`Gestart door ${form.elements.name.value.trim()||'Anoniem'}`;document.querySelector('[data-preview-body]').textContent=body.value.trim();const source=document.querySelector('[data-preview-source]');source.hidden=!form.elements.source.value;source.href=form.elements.source.value;source.textContent=form.elements.source.value;hidePanels();preview.hidden=false;preview.focus();}
  form.addEventListener('submit',event=>{event.preventDefault();document.querySelector('[data-composer-status]').textContent='';if(!validate()){document.querySelector('[data-composer-status]').textContent='Controleer de gemarkeerde velden en bevestigingen.';form.querySelector('[aria-invalid="true"], [data-required-check]:not(:checked)')?.focus();return;}showPreview();});
  document.querySelector('[data-edit-draft]').addEventListener('click',showComposer);
  document.querySelector('[data-save-draft]').addEventListener('click',()=>{const lines=['DE ONWIJZE WIJSHEDEN — LOKAAL FORUMCONCEPT','',`RUIMTE: ${form.elements.space.value}`,`TITEL: ${title.value.trim()}`,`NAAM/PSEUDONIEM: ${form.elements.name.value.trim()||'Anoniem'}`,'','GESPREKSSTART',body.value.trim(),'','BRON',form.elements.source.value||'Niet opgegeven.','','Dit bestand werd lokaal gemaakt en niet automatisch verzonden.'];const blob=new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='forumconcept.txt';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);});
  const launchParams=new URLSearchParams(location.search);render();
  if(launchParams.get('start')==='1'){
    const requestedSpace=launchParams.get('ruimte');if(requestedSpace&&[...form.elements.space.options].some(option=>option.value===requestedSpace))form.elements.space.value=requestedSpace;
    title.value=launchParams.get('titel')||'';counters();showComposer();
  }
})();
