(function () {
  const o = (...pairs) => pairs.map(([text, result]) => ({ text, result }));
  window.MENSLAB_QUIZZES = [
    {
      id: 'beweging-vandaag',
      title: 'Welke kleine beweging heb jij vandaag nodig?',
      eyebrow: 'Vandaag · kleine beweging',
      resultOrder: ['vertragen', 'benoemen', 'begrenzen', 'verbinden', 'kiezen'],
      questions: [
        { text: 'Wat schuurt vandaag het meest?', options: o(['Mijn tempo ligt hoger dan goed voelt.', 'vertragen'], ['Ik voel veel, maar krijg er geen woorden voor.', 'benoemen'], ['Er komt meer op mij af dan ik wil dragen.', 'begrenzen'], ['Ik probeer iets te lang alleen vast te houden.', 'verbinden'], ['Ik blijf rond dezelfde beslissing draaien.', 'kiezen']) },
        { text: 'Welke vorm van opluchting klinkt nu het aantrekkelijkst?', options: o(['Even nergens onmiddellijk op reageren.', 'vertragen'], ['Eindelijk precies begrijpen wat er in mij omgaat.', 'benoemen'], ['Iets mogen weigeren of uitstellen.', 'begrenzen'], ['Hardop kunnen zeggen wat me bezighoudt.', 'verbinden'], ['Eén richting nemen en de rest laten rusten.', 'kiezen']) },
        { text: 'Wanneer je aandacht afdwaalt, waar trekt ze dan naartoe?', options: o(['Naar alles wat nog snel moet gebeuren.', 'vertragen'], ['Naar een onduidelijk gevoel op de achtergrond.', 'benoemen'], ['Naar wat anderen nog van mij verwachten.', 'begrenzen'], ['Naar iemand die ik eigenlijk wil spreken.', 'verbinden'], ['Naar iets wat ik maar niet beslis.', 'kiezen']) },
        { text: 'Welke zin komt vandaag het dichtst in de buurt?', options: o(['Ik hoef niet alles op dit tempo te doen.', 'vertragen'], ['Ik wil weten wat dit gevoel eigenlijk is.', 'benoemen'], ['Niet alles wat kan, hoeft door mij.', 'begrenzen'], ['Ik hoef dit niet alleen uit te zoeken.', 'verbinden'], ['Een kleine keuze is ook een keuze.', 'kiezen']) },
        { text: 'Wat stel je misschien een beetje uit?', options: o(['Een echte pauze nemen.', 'vertragen'], ['Stilstaan bij wat iets met me deed.', 'benoemen'], ['Een grens duidelijk maken.', 'begrenzen'], ['Iemand om nabijheid of hulp vragen.', 'verbinden'], ['Een eerste stap zetten.', 'kiezen']) },
        { text: 'Wat zou vanavond als een goede kleine verschuiving voelen?', options: o(['Dat mijn hoofd iets minder gejaagd is.', 'vertragen'], ['Dat ik mezelf beter kan verstaan.', 'benoemen'], ['Dat er minder op mijn bord ligt.', 'begrenzen'], ['Dat ik me iets minder alleen voel.', 'verbinden'], ['Dat één los eindje een richting kreeg.', 'kiezen']) }
      ],
      results: {
        vertragen: { kicker: 'Mogelijke beweging voor vandaag', title: 'Vertragen', summary: 'In je antwoorden klinkt behoefte aan ruimte tussen prikkel en reactie. Niet om stil te vallen, maar om weer iets te kunnen kiezen.', strength: 'Vertragen kan details, lichaamssignalen en alternatieven opnieuw zichtbaar maken.', friction: 'Een pauze lost niet automatisch op wat structureel te veel of onveilig is.', counter: 'Wanneer geeft tempo je juist energie en helderheid?', experiment: 'Kies één overgangsmoment. Wacht daar bewust tien seconden voordat je verdergaat.', readHref: 'onderwerpen/stress.html', readTitle: 'Stress', readLabel: 'Lees het dossier Stress →', readReason: 'Deze tekst maakt onderscheid tussen een korte pauze, herstel en omstandigheden die structureel te veel blijven.' },
        benoemen: { kicker: 'Mogelijke beweging voor vandaag', title: 'Benoemen', summary: 'Er lijkt iets te vragen om preciezere taal. Een naam hoeft het gevoel niet vast te zetten; ze kan alleen wat houvast geven.', strength: 'Nauwkeuriger woorden kunnen helpen onderscheiden wat nu eigenlijk aandacht vraagt.', friction: 'Niet iedere ervaring laat zich meteen vangen, en een label kan soms te smal worden.', counter: 'Wanneer helpt het je meer om iets nog even woordeloos te laten?', experiment: 'Vervang vandaag één keer “goed” of “slecht” door twee preciezere woorden.', readHref: 'onderwerpen/emotieregulatie.html', readTitle: 'Emotieregulatie', readLabel: 'Lees het dossier Emotieregulatie →', readReason: 'Deze tekst verdiept wat woorden, lichaam, context en verschillende regulatiestrategieën wel en niet kunnen doen.' },
        begrenzen: { kicker: 'Mogelijke beweging voor vandaag', title: 'Begrenzen', summary: 'Je antwoorden wijzen op veel vragen, verwachtingen of verantwoordelijkheden tegelijk. Misschien is minder dragen nu een vorm van zorg.', strength: 'Een grens kan tijd, aandacht en relaties eerlijker maken.', friction: 'Grenzen zijn niet altijd vrij te kiezen; afhankelijkheid, macht en veiligheid spelen mee.', counter: 'Welke verantwoordelijkheid wil je juist bewust blijven dragen?', experiment: 'Kies één verzoek waarop je niet meteen antwoordt. Zeg: “Ik kom hier later op terug.”', readHref: 'onderwerpen/boosheid.html', readTitle: 'Boosheid', readLabel: 'Lees het dossier Boosheid →', readReason: 'Deze tekst onderzoekt hoe een grenssignaal informatie kan geven, zonder iedere impuls automatisch tot juist bevel te maken.' },
        verbinden: { kicker: 'Mogelijke beweging voor vandaag', title: 'Verbinden', summary: 'Er lijkt iets te willen worden gedeeld, gevraagd of samen gedragen. Verbinding kan ook klein beginnen.', strength: 'Een ander perspectief of aanwezige ander kan isolement verzachten en nieuwe informatie geven.', friction: 'Niet iedere persoon of omgeving is veilig genoeg voor openheid.', counter: 'Wanneer beschermt alleen zijn juist iets waardevols in jou?', experiment: 'Stuur één betrouwbare persoon een eenvoudige zin: “Heb je binnenkort even tijd om te luisteren?”', readHref: 'onderwerpen/hechting.html', readTitle: 'Hechting', readLabel: 'Lees het dossier Hechting →', readReason: 'Deze tekst plaatst nabijheid naast veiligheid, autonomie, cultuur en de verschillen tussen relaties.' },
        kiezen: { kicker: 'Mogelijke beweging voor vandaag', title: 'Kiezen', summary: 'Je antwoorden blijven rond een richting of eerste stap bewegen. Misschien hoeft de keuze niet perfect te zijn om bruikbaar te worden.', strength: 'Een kleine keuze kan informatie opleveren die verder nadenken niet geeft.', friction: 'Snel beslissen is niet altijd wijs wanneer gevolgen groot of moeilijk omkeerbaar zijn.', counter: 'Welke twijfel bevat informatie die je nog werkelijk nodig hebt?', experiment: 'Maak één keuze die klein, veilig en omkeerbaar is. Behandel haar als proef, niet als eindoordeel.', readHref: 'veranderroute.html', readTitle: 'De Veranderroute', readLabel: 'Volg de bestaande Veranderroute →', readReason: 'Deze route behandelt verandering als een proef met context, terugval en kleine haalbare stappen — niet als één grote beslissing.' }
      }
    },
    {
      id: 'luisteren-of-repareren',
      title: 'Luister jij — of begin je te repareren?',
      eyebrow: 'Gesprekken · nabijheid',
      resultOrder: ['ruimte', 'verhelderen', 'meedragen', 'oplossen'],
      questions: [
        { text: 'Iemand begint over een moeilijke dag. Wat doe je meestal eerst?', options: o(['Ik laat vertellen en probeer niet te onderbreken.', 'ruimte'], ['Ik stel een vraag om beter te begrijpen wat er gebeurde.', 'verhelderen'], ['Ik benoem dat het zwaar of pijnlijk klinkt.', 'meedragen'], ['Ik zoek meteen naar iets dat praktisch kan helpen.', 'oplossen']) },
        { text: 'Wanneer een verhaal lang wordt, waar gaat je aandacht naartoe?', options: o(['Naar het tempo en de stiltes van de ander.', 'ruimte'], ['Naar wat nog onduidelijk of tegenstrijdig is.', 'verhelderen'], ['Naar het gevoel onder de woorden.', 'meedragen'], ['Naar de kern en de mogelijke volgende stap.', 'oplossen']) },
        { text: 'Welke reactie voelt het natuurlijkst?', options: o(['“Neem je tijd.”', 'ruimte'], ['“Wat bedoel je precies met…?”', 'verhelderen'], ['“Ik kan me voorstellen dat dit je raakt.”', 'meedragen'], ['“Zal ik even met je meedenken?”', 'oplossen']) },
        { text: 'Wat vind je het lastigst in zo’n gesprek?', options: o(['De stilte niet meteen vullen.', 'ruimte'], ['Niet te veel vragen achter elkaar stellen.', 'verhelderen'], ['Niet alle emoties zelf mee naar huis nemen.', 'meedragen'], ['Geen oplossing geven wanneer ik er één zie.', 'oplossen']) },
        { text: 'Wanneer weet je dat het gesprek geholpen heeft?', options: o(['De ander kreeg ruimte om het eigen verhaal te horen.', 'ruimte'], ['Het probleem of verlangen werd helderder.', 'verhelderen'], ['De ander voelde zich minder alleen in wat er speelt.', 'meedragen'], ['Er ontstond een concrete mogelijkheid om verder te gaan.', 'oplossen']) },
        { text: 'Wat zou je vaker willen kunnen?', options: o(['Aanwezig blijven zonder iets te hoeven doen.', 'ruimte'], ['Eén goede vraag stellen in plaats van vijf snelle.', 'verhelderen'], ['Meevoelen zonder mezelf kwijt te raken.', 'meedragen'], ['Eerst vragen of advies welkom is.', 'oplossen']) }
      ],
      results: {
        ruimte: { kicker: 'Wat in je antwoorden opvalt', title: 'Ruimte laten', summary: 'Je neigt naar aanwezigheid zonder onmiddellijk richting te geven. Dat kan een ander helpen het eigen verhaal te horen.', strength: 'Stilte en onverdeelde aandacht kunnen een gesprek minder gehaast maken.', friction: 'Alleen ruimte laten kan afstandelijk voelen wanneer iemand om duidelijke betrokkenheid of hulp vraagt.', counter: 'Wanneer wacht je zo lang dat je eigen stem uit het gesprek verdwijnt?', experiment: 'Laat in één gesprek na een antwoord bewust drie seconden stilte vallen.', readHref: 'onderwerpen/de-ander-verandert-je.html', readTitle: 'De ander verandert je', readLabel: 'Lees het dossier De ander verandert je →', readReason: 'Deze tekst onderzoekt responsiviteit én de grens tussen ruimte geven, jezelf aanpassen en verdwijnen uit het contact.' },
        verhelderen: { kicker: 'Wat in je antwoorden opvalt', title: 'Verhelderen', summary: 'Je probeert te begrijpen door precies te vragen en verbanden zichtbaar te maken. Je luistert actief met je nieuwsgierigheid.', strength: 'Een goede vraag kan aannames verminderen en een vaag probleem scherper maken.', friction: 'Veel vragen kunnen als een interview voelen wanneer iemand vooral erkenning nodig heeft.', counter: 'Wanneer heeft de ander geen extra vraag maar gewoon gezelschap nodig?', experiment: 'Stel één open vraag en vat daarna samen wat je hoorde, zonder een tweede vraag.', readHref: 'onderwerpen/ervaring.html', readTitle: 'Ervaring', readLabel: 'Lees het dossier Ervaring →', readReason: 'Deze tekst laat zien waarom jouw interpretatie en de beleving van de ander nooit volledig samenvallen.' },
        meedragen: { kicker: 'Wat in je antwoorden opvalt', title: 'Meevoelen', summary: 'Je aandacht gaat snel naar de emotionele laag en het gevoel van de ander. Je probeert nabijheid te maken.', strength: 'Erkenning kan iemand helpen zich gezien en minder alleen te voelen.', friction: 'Meevoelen kan overgaan in overnemen, invullen of jezelf te lang verantwoordelijk voelen.', counter: 'Welke gevoelens zijn van de ander en hoeven niet door jou te worden opgelost?', experiment: 'Benoem één keer wat je denkt te horen en voeg toe: “Klopt dat voor jou?”', readHref: 'onderwerpen/hechting.html', readTitle: 'Hechting', readLabel: 'Lees het dossier Hechting →', readReason: 'Deze tekst verdiept hoe nabijheid en co-regulatie kunnen helpen, maar ook relatiespecifiek en begrensd blijven.' },
        oplossen: { kicker: 'Wat in je antwoorden opvalt', title: 'Samen oplossen', summary: 'Je luistert met een oog voor mogelijkheden en beweging. Je wilt dat het gesprek ergens toe leidt.', strength: 'Praktisch denken is waardevol wanneer iemand vastzit en werkelijk om hulp vraagt.', friction: 'Een goede oplossing kan te vroeg komen en daardoor de ervaring van de ander overslaan.', counter: 'Kan het soms gebeuren dat snel oplossen óók jouw ongemak met machteloosheid vermindert?', experiment: 'Vraag vóór je advies geeft: “Wil je dat ik luister, vragen stel of meedenk?”', readHref: 'onderwerpen/de-ander-verandert-je.html', readTitle: 'De ander verandert je', readLabel: 'Lees het dossier De ander verandert je →', readReason: 'Deze tekst onderzoekt wanneer steun werkelijk responsief is en wanneer helpen de autonomie van de ander kleiner kan maken.' }
      }
    },
    {
      id: 'waar-komt-je-ja-vandaan',
      title: 'Waar komt jouw ja vandaan?',
      eyebrow: 'Keuzes · motivatie',
      resultOrder: ['volmondig', 'harmonie', 'verantwoordelijkheid', 'automatisch', 'voorlopig'],
      questions: [
        { text: 'Iemand vraagt je iets onverwachts. Wat gebeurt er meestal eerst?', options: o(['Ik voel vrij snel echte zin of geen zin.', 'volmondig'], ['Ik kijk wat mijn antwoord met de ander zal doen.', 'harmonie'], ['Ik denk na over wat van mij verwacht mag worden.', 'verantwoordelijkheid'], ['Ik hoor mezelf al ja zeggen voordat ik heb nagedacht.', 'automatisch'], ['Ik wil eerst wat meer informatie of tijd.', 'voorlopig']) },
        { text: 'Hoe voelt een ja achteraf meestal in je lichaam?', options: o(['Ruim en energiek.', 'volmondig'], ['Rustig omdat de relatie goed blijft.', 'harmonie'], ['Stevig omdat ik deed wat nodig was.', 'verantwoordelijkheid'], ['Zwaarder dan ik tijdens het antwoorden merkte.', 'automatisch'], ['Nog open: ik blijf voelen of het echt past.', 'voorlopig']) },
        { text: 'Welke zin is voor jou het moeilijkst?', options: o(['“Dit wil ik echt niet.”', 'volmondig'], ['“Je zult dit misschien jammer vinden, maar…”', 'harmonie'], ['“Dit is niet mijn verantwoordelijkheid.”', 'verantwoordelijkheid'], ['“Ik wil eerst nadenken voordat ik antwoord.”', 'automatisch'], ['“Mijn antwoord is voorlopig, niet definitief.”', 'voorlopig']) },
        { text: 'Wat maakt een ja voor jou het meest betekenisvol?', options: o(['Dat het van binnenuit klopt.', 'volmondig'], ['Dat het verbinding of samenwerking beschermt.', 'harmonie'], ['Dat ik betrouwbaar ben en iets draag wat ertoe doet.', 'verantwoordelijkheid'], ['Dat ik snel beschikbaar en behulpzaam kan zijn.', 'automatisch'], ['Dat er ruimte blijft om onderweg bij te sturen.', 'voorlopig']) },
        { text: 'Wanneer merk je meestal dat een ja niet goed paste?', options: o(['Als mijn aanvankelijke energie snel verdwijnt.', 'volmondig'], ['Als ik wrevel voel tegenover degene voor wie ik het deed.', 'harmonie'], ['Als plicht alle andere grenzen verdringt.', 'verantwoordelijkheid'], ['Als mijn lichaam pas later protesteert.', 'automatisch'], ['Als onduidelijkheid te lang blijft aanslepen.', 'voorlopig']) },
        { text: 'Welke kleine verandering zou jouw ja eerlijker maken?', options: o(['Vaker hardop zeggen waar ik werkelijk zin in heb.', 'volmondig'], ['Teleurstelling niet meteen als relatiebreuk zien.', 'harmonie'], ['Verschil maken tussen verantwoordelijkheid en oververantwoordelijkheid.', 'verantwoordelijkheid'], ['Een standaardpauze nemen vóór ik antwoord.', 'automatisch'], ['Duidelijk zeggen wanneer ik opnieuw beslis.', 'voorlopig']) }
      ],
      results: {
        volmondig: { kicker: 'De sterkste lijn in je antwoorden', title: 'Het volmondige ja', summary: 'Je zoekt naar een ja dat van binnenuit gedragen voelt. Zin, betekenis en persoonlijke instemming wegen zwaar.', strength: 'Een zelfgedragen keuze kan energie en helderheid geven.', friction: 'Niet alles wat waardevol is voelt onmiddellijk aantrekkelijk; zorg en inzet kunnen ook moeite kosten.', counter: 'Wanneer ontstaat betrokkenheid pas nadat je begonnen bent?', experiment: 'Noem bij je volgende ja één concrete reden waarom jij dit zelf wilt.', readHref: 'onderwerpen/persoonlijkheid.html', readTitle: 'Persoonlijkheid', readLabel: 'Lees het dossier Persoonlijkheid →', readReason: 'Deze tekst plaatst persoonlijke waarden naast gewoonten, context en veranderlijke rollen — zodat “van binnenuit” niet het enige verhaal wordt.' },
        harmonie: { kicker: 'De sterkste lijn in je antwoorden', title: 'Het harmonieja', summary: 'Je antwoord houdt sterk rekening met verbinding, sfeer en de mogelijke teleurstelling van anderen.', strength: 'Afstemming en zorg voor relaties zijn echte menselijke waarden, geen zwakte.', friction: 'Een relatie kan uiterlijk rustig blijven terwijl jij innerlijk steeds minder ruimte ervaart.', counter: 'Welke relatie kan een eerlijk nee waarschijnlijk beter dragen dan je vreest?', experiment: 'Oefen één vriendelijke grenszin: “Ik wil helpen, maar dit lukt me nu niet.”', readHref: 'onderwerpen/de-ander-verandert-je.html', readTitle: 'De ander verandert je', readLabel: 'Lees het dossier De ander verandert je →', readReason: 'Deze tekst onderzoekt afstemming, steun en zelfverlies zonder zorg voor relaties als zwakte weg te zetten.' },
        verantwoordelijkheid: { kicker: 'De sterkste lijn in je antwoorden', title: 'Het verantwoordelijke ja', summary: 'Je ja lijkt vaak verbonden met betrouwbaarheid, plicht en wat volgens jou werkelijk gedragen moet worden.', strength: 'Verantwoordelijkheid kan anderen veiligheid en continuïteit geven.', friction: 'Wie veel kan dragen, krijgt soms ook te veel toegeschoven — of schuift het zichzelf toe.', counter: 'Welke taak is belangrijk, maar hoeft niet noodzakelijk door jou te worden gedaan?', experiment: 'Vraag bij één taak: “Ben ik verantwoordelijk, betrokken of alleen beschikbaar?”', readHref: 'onderwerpen/hechting.html', readTitle: 'Hechting', readLabel: 'Lees het dossier Hechting →', readReason: 'Deze tekst laat zien hoe zorg, afhankelijkheid, veiligheid en verantwoordelijkheid tussen relaties kunnen verschillen.' },
        automatisch: { kicker: 'De sterkste lijn in je antwoorden', title: 'Het snelle ja', summary: 'Je antwoord is soms al vertrokken voordat je wensen, grenzen of beschikbare energie volledig zijn ingehaald.', strength: 'Spontane bereidheid kan warm, gul en daadkrachtig zijn.', friction: 'Een snel ja kan later veranderen in vermoeidheid, uitstel of stille wrevel.', counter: 'Wanneer is jouw snelheid juist een betrouwbare vorm van intuïtie?', experiment: 'Gebruik vandaag één standaardzin: “Ik kijk even of het past en laat het je weten.”', readHref: 'onderwerpen/gewoontes.html', readTitle: 'Gewoontes', readLabel: 'Lees het dossier Gewoontes →', readReason: 'Deze tekst onderzoekt automatische reacties zonder ze te reduceren tot karakter of een eenvoudig gebrek aan wilskracht.' },
        voorlopig: { kicker: 'De sterkste lijn in je antwoorden', title: 'Het voorlopige ja', summary: 'Je houdt graag ruimte om te onderzoeken, informatie te verzamelen of later bij te sturen.', strength: 'Voorlopigheid kan nuance en leervermogen beschermen.', friction: 'Een open antwoord kan voor jou veilig voelen maar voor anderen lang onduidelijk blijven.', counter: 'Wanneer weet je eigenlijk al genoeg om een richting te kiezen?', experiment: 'Koppel aan één voorlopig antwoord een helder moment: “Morgen om vier uur beslis ik.”', readHref: 'veranderroute.html', readTitle: 'De Veranderroute', readLabel: 'Volg de bestaande Veranderroute →', readReason: 'Deze route laat zien hoe je een richting als kleine proef kunt behandelen, met ruimte om bij te sturen.' }
      }
    },
    {
      id: 'wie-zit-aan-het-stuur',
      title: 'Wie zit er vandaag aan jouw stuur?',
      eyebrow: 'Persoonlijkheid · tijdelijke hoofdrol',
      theoryHref: 'onderwerpen/persoonlijkheid.html',
      theoryLabel: 'Waarom je persoonlijkheid rijker is dan één type →',
      resultOrder: ['motor', 'situatielezer', 'kompasdrager', 'verhalenmaker'],
      questions: [
        { text: 'Je stapt een kamer binnen waar je bijna niemand kent. Waar begint jouw gedrag meestal?', options: o(['Bij een vertrouwde neiging: ik kijk eerst, of ik stap juist meteen op iemand af.', 'motor'], ['Bij de kamer zelf: wie is er, hoe veilig voelt het en wat lijkt hier passend?', 'situatielezer'], ['Bij mijn bedoeling: waarvoor ben ik hier en wat wil ik niet uit het oog verliezen?', 'kompasdrager'], ['Bij de rol waarin ik mezelf daar voel belanden: nieuwkomer, helper, buitenstaander of gangmaker.', 'verhalenmaker']) },
        { text: 'Je zorgvuldig gemaakte plan valt op dinsdag om 10.17 uur uit elkaar. Wat neemt als eerste over?', options: o(['Ik lees opnieuw wat dit moment nu van me vraagt.', 'situatielezer'], ['Ik val terug op mijn bekende ritme — nuttig of lichtelijk voorspelbaar.', 'motor'], ['Ik vraag welke richting nog altijd belangrijk is, ook zonder het oorspronkelijke plan.', 'kompasdrager'], ['Mijn hoofd maakt er meteen een hoofdstuk van: “Natuurlijk gebeurt dit weer” of “Dit wordt een goed verhaal.”', 'verhalenmaker']) },
        { text: 'Iemand zegt: “Dat is zó typisch jij.” Welke reactie zit het dichtst in de buurt?', options: o(['“Bij jou misschien. In een andere omgeving ben ik heel anders.”', 'situatielezer'], ['“Ja, dat patroon is ondertussen vrij goed gedocumenteerd.”', 'motor'], ['“Hopelijk zie je daarin ook wat ik belangrijk probeer te vinden.”', 'kompasdrager'], ['“Welke versie van mij bedoel je precies? Er zijn meerdere seizoenen.”', 'verhalenmaker']) },
        { text: 'Bij een lastige keuze, welke vraag trekt het hardst aan je mouw?', options: o(['Wat wil ik dat deze keuze zegt over waar ik voor sta?', 'kompasdrager'], ['Wat doe ik in dit soort situaties doorgaans?', 'motor'], ['Wat is hier werkelijk mogelijk, met deze mensen en deze omstandigheden?', 'situatielezer'], ['Welk oud verhaal herhaal ik — en welk verhaal wil ik misschien herzien?', 'verhalenmaker']) },
        { text: 'Je wilt iets aan jezelf veranderen. Waar krijg je het meeste vertrouwen van?', options: o(['Een kleine gewoonte die ik vaak genoeg kan herhalen.', 'motor'], ['Een omgeving bouwen waarin het nieuwe gedrag meer kans krijgt.', 'situatielezer'], ['Een reden die belangrijk genoeg is om moeite voor te doen.', 'kompasdrager'], ['Een ander verhaal over wie ik al ben en nog aan het worden ben.', 'verhalenmaker']) },
        { text: 'Een oude bekende ziet je na tien jaar terug. Wat hoop je stiekem dat die opmerkt?', options: o(['Dat de herkenbare kern er nog is, alleen iets beter afgesteld.', 'motor'], ['Dat ik in nieuwe werelden ook nieuwe kanten heb leren gebruiken.', 'situatielezer'], ['Dat mijn keuzes duidelijker laten zien wat ik belangrijk vind.', 'kompasdrager'], ['Dat ik niet meer volledig woon in het verhaal dat die persoon van mij kende.', 'verhalenmaker']) },
        { text: 'Wat ergert je het meest aan een slechte persoonlijkheidstest?', options: o(['Dat één losse vraag moet bewijzen hoe ik “altijd” ben.', 'motor'], ['Dat de situatie nergens mag meedoen.', 'situatielezer'], ['Dat gedrag wordt verward met de reden waarom ik iets doe.', 'kompasdrager'], ['Dat een leuke titel plots mijn hele identiteit gijzelt.', 'verhalenmaker']) },
        { text: 'Als jouw tijdelijke hoofdrolspeler vandaag een naamkaartje kreeg, wat zou erop staan?', options: o(['De Vaste Motor — herkenbaar, herhaalbaar en soms toe aan een andere versnelling.', 'motor'], ['De Situatielezer — voelt de kamer voordat de kamer zichzelf begrijpt.', 'situatielezer'], ['De Kompasdrager — wil weten waar dit alles eigenlijk naartoe mag.', 'kompasdrager'], ['De Verhalenmaker — leeft én verzorgt ondertussen de voice-over.', 'verhalenmaker']) }
      ],
      results: {
        motor: { kicker: 'Vandaag de meeste spreektijd', title: 'De Vaste Motor', summary: 'In je antwoorden begon persoonlijkheid vaak bij wat zich herhaalt: vertrouwde voorkeuren, gewoonten en manieren van reageren. Dat patroon kan herkenbaar zijn zonder je hele verklaring te zijn.', strength: 'Regelmaat kan betrouwbaarheid, zelfkennis en een stevig vertrekpunt geven.', friction: 'Wat vaak gebeurt, kan vanzelf gaan voelen alsof het niet anders kán — terwijl context en oefening soms meer ruimte geven.', counter: 'In welke situatie verras je jezelf juist en gedraag je je opvallend anders?', experiment: 'Kies één herkenbaar patroon en noteer drie momenten: wanneer verschijnt het, wanneer niet en wat was er anders?', readHref: 'onderwerpen/gewoontes.html', readTitle: 'Gewoontes', readLabel: 'Lees het dossier Gewoontes →', readReason: 'Deze tekst onderzoekt hoe herhaling en context een vaste motor kunnen bouwen, zonder gewoonte gelijk te stellen aan identiteit.' },
        situatielezer: { kicker: 'Vandaag de meeste spreektijd', title: 'De Situatielezer', summary: 'Je antwoorden gaven veel gewicht aan de kamer, de mensen en de werkelijke omstandigheden. Je ziet persoonlijkheid niet los van waar en met wie gedrag verschijnt.', strength: 'Contextgevoeligheid kan nuance, afstemming en een rijker gedragsrepertoire geven.', friction: 'Wie de kamer heel goed leest, kan het eigen signaal soms pas laat horen — of achteraf niet weten wat nu werkelijk van zichzelf kwam.', counter: 'Welke waarde of grens wil je meenemen, ook wanneer de omgeving iets anders beloont?', experiment: 'Vergelijk één terugkerend gedrag in twee situaties. Welke persoon, verwachting of mate van veiligheid verandert het?', readHref: 'onderwerpen/persoonlijkheid.html', readTitle: 'Persoonlijkheid', readLabel: 'Lees het dossier Persoonlijkheid →', readReason: 'Deze tekst verdiept waarom gedrag per situatie kan wisselen en brede trekken toch enige samenhang kunnen tonen.' },
        kompasdrager: { kicker: 'Vandaag de meeste spreektijd', title: 'De Kompasdrager', summary: 'In je antwoorden kregen doelen, waarden en redenen veel invloed. Voor jou wordt persoonlijkheid vooral zichtbaar in de richting die iemand probeert te kiezen.', strength: 'Een kompas kan samenhang geven wanneer stemming en omstandigheden wisselen.', friction: 'Een mooie richting kan draagkracht, gewoonte of echte beperkingen onderschatten. Waarden vertellen niet automatisch welke stap nu haalbaar is.', counter: 'Wanneer deed je iets waardevols zonder dat het vooraf als een bewuste waarde voelde?', experiment: 'Maak één keuzezin af: “Dit is voor mij belangrijk, en de kleinste haalbare vorm ervan is…”', readHref: 'onderwerpen/persoonlijkheid.html', readTitle: 'Persoonlijkheid', readLabel: 'Lees het dossier Persoonlijkheid →', readReason: 'Deze tekst zet waarden en doelen naast trekken, context en levensverhaal, zodat één mooi kompas niet alles hoeft te verklaren.' },
        verhalenmaker: { kicker: 'Vandaag de meeste spreektijd', title: 'De Verhalenmaker', summary: 'Je antwoorden gingen vaak naar rollen, hoofdstukken en de betekenis die je aan verandering geeft. Je kijkt niet alleen naar wat je doet, maar ook naar wie je daardoor denkt te zijn.', strength: 'Een levensverhaal kan losse ervaringen verbinden, richting geven en verandering begrijpelijk maken.', friction: 'Een oud verhaal kan nieuwe informatie wegredigeren. Ook een prachtig zelfverhaal blijft een selectie, geen volledige opname van je leven.', counter: 'Welke recente gebeurtenis past verrassend slecht in het verhaal dat je meestal over jezelf vertelt?', experiment: 'Schrijf één vaste zelfzin op en voeg toe: “Behalve wanneer…” Laat minstens twee echte uitzonderingen binnen.', readHref: 'onderwerpen/persoonlijkheid.html', readTitle: 'Persoonlijkheid', readLabel: 'Lees het dossier Persoonlijkheid →', readReason: 'Deze tekst behandelt narratieve identiteit als één laag van persoonlijkheid — betekenisvol, maar nooit de volledige opname.' }
      }
    }
  ];
})();
