(function () {
  const o = (...pairs) => pairs.map(([text, result]) => ({ text, result }));
  const s = (id, text, feedback, signals) => ({ id, text, feedback, signals });
  window.MENSLAB_QUIZZES = [
    {
      id: 'beweging-vandaag',
      title: 'Wat wil je vandaag anders aanpakken?',
      eyebrow: 'Vandaag · vijf concrete richtingen',
      mode: 'allocation',
      tokenBudget: 5,
      customEyebrow: 'Kies waar je iets mee wilt doen',
      customTitle: 'Verdeel vijf vonkjes over wat vandaag jouw aandacht vraagt.',
      customIntro: 'Geef meer vonkjes aan de richting waar je vandaag werkelijk iets mee wilt doen. Geef niets aan wat niet speelt. Je hoeft ze niet gelijk te verdelen.',
      customMissLabel: 'Geen van deze richtingen past vandaag',
      customMissHelp: 'Dan forceren we geen richting en blijft de spiegel open.',
      gameOptions: [
        { result: 'vertragen', symbol: 'Ⅱ', label: 'Vertragen', copy: 'Ruimte tussen prikkel en reactie.' },
        { result: 'benoemen', symbol: 'Aa', label: 'Benoemen', copy: 'Woorden zoeken voor wat nog vaag is.' },
        { result: 'begrenzen', symbol: '│', label: 'Begrenzen', copy: 'Minder dragen of niet meteen antwoorden.' },
        { result: 'verbinden', symbol: '∞', label: 'Verbinden', copy: 'Iets delen, vragen of samen dragen.' },
        { result: 'kiezen', symbol: '↗', label: 'Kiezen', copy: 'Een kleine richting als proef nemen.' }
      ],
      resultOrder: ['vertragen', 'benoemen', 'begrenzen', 'verbinden', 'kiezen'],
      questions: [
        { text: 'Wat schuurt vandaag het meest?', options: o(['Mijn tempo ligt hoger dan goed voelt.', 'vertragen'], ['Ik voel veel, maar krijg er geen woorden voor.', 'benoemen'], ['Er komt meer op mij af dan ik wil dragen.', 'begrenzen'], ['Ik probeer iets te lang alleen vast te houden.', 'verbinden'], ['Ik blijf rond dezelfde beslissing draaien.', 'kiezen']) },
        { text: 'Welke vorm van opluchting klinkt nu het aantrekkelijkst?', options: o(['Even nergens onmiddellijk op reageren.', 'vertragen'], ['Eindelijk precies begrijpen wat er in mij omgaat.', 'benoemen'], ['Iets mogen weigeren of uitstellen.', 'begrenzen'], ['Hardop kunnen zeggen wat me bezighoudt.', 'verbinden'], ['Eén richting nemen en de rest laten rusten.', 'kiezen']) },
        { text: 'Wanneer je aandacht afdwaalt, waar trekt ze dan naartoe?', options: o(['Naar alles wat nog snel moet gebeuren.', 'vertragen'], ['Naar een onduidelijk gevoel op de achtergrond.', 'benoemen'], ['Naar wat anderen nog van mij verwachten.', 'begrenzen'], ['Naar iemand die ik eigenlijk wil spreken.', 'verbinden'], ['Naar iets wat ik maar niet beslis.', 'kiezen']) },
        { text: 'Welke zin komt vandaag het dichtst in de buurt?', options: o(['Ik hoef niet alles op dit tempo te doen.', 'vertragen'], ['Ik wil weten wat dit gevoel eigenlijk is.', 'benoemen'], ['Niet alles wat kan, hoeft door mij.', 'begrenzen'], ['Ik hoef dit niet alleen uit te zoeken.', 'verbinden'], ['Een kleine keuze is ook een keuze.', 'kiezen']) },
        { text: 'Wat stel je misschien een beetje uit?', options: o(['Een echte pauze nemen.', 'vertragen'], ['Stilstaan bij wat iets met me deed.', 'benoemen'], ['Een grens duidelijk maken.', 'begrenzen'], ['Iemand om nabijheid of hulp vragen.', 'verbinden'], ['Een eerste stap zetten.', 'kiezen']) },
        { text: 'Wat zou vanavond als een goede kleine verschuiving voelen?', options: o(['Dat mijn hoofd iets minder gejaagd is.', 'vertragen'], ['Dat ik mezelf beter kan verstaan.', 'benoemen'], ['Dat er minder op mijn bord ligt.', 'begrenzen'], ['Dat ik me iets minder alleen voel.', 'verbinden'], ['Dat één los eindje een richting kreeg.', 'kiezen']) }
      ],
      results: {
        vertragen: { kicker: 'Mogelijke beweging voor vandaag', title: 'Vertragen', summary: 'In je antwoorden klinkt behoefte aan ruimte tussen prikkel en reactie. Niet om stil te vallen, maar om weer iets te kunnen kiezen.', strength: 'Vertragen kan details, lichaamssignalen en alternatieven opnieuw zichtbaar maken.', friction: 'Een pauze lost niet automatisch op wat structureel te veel of onveilig is.', counter: 'Wanneer geeft tempo je juist energie en helderheid?', experiment: 'Kies één overgangsmoment. Wacht daar bewust tien seconden voordat je verdergaat.', readHref: 'onderwerpen/stress.html', readTitle: 'Stress', readLabel: 'Lees het dossier Stress →', readReason: 'Deze tekst maakt onderscheid tussen een korte pauze, herstel en omstandigheden die structureel te veel blijven.' },
        benoemen: { kicker: 'Mogelijke beweging voor vandaag', title: 'Benoemen', summary: 'Er lijkt iets te vragen om preciezere taal. Een naam hoeft het gevoel niet vast te zetten; ze kan alleen wat houvast geven.', strength: 'Nauwkeuriger woorden kunnen helpen onderscheiden wat nu eigenlijk aandacht vraagt.', friction: 'Niet iedere ervaring laat zich meteen vangen, en een label kan soms te smal worden.', counter: 'Wanneer helpt het je meer om iets nog even woordeloos te laten?', experiment: 'Vervang vandaag één keer “goed” of “slecht” door twee preciezere woorden.', readHref: 'onderwerpen/emotieregulatie.html', readTitle: 'Emotieregulatie', readLabel: 'Lees het dossier Emotieregulatie →', readReason: 'Deze tekst verdiept wat woorden, lichaam, context en verschillende regulatiestrategieën wel en niet kunnen doen.' },
        begrenzen: { kicker: 'Mogelijke beweging voor vandaag', title: 'Begrenzen', summary: 'Je antwoorden wijzen op veel vragen, verwachtingen of verantwoordelijkheden tegelijk. Misschien is minder dragen nu een vorm van zorg.', strength: 'Een grens kan tijd, aandacht en relaties eerlijker maken.', friction: 'Grenzen zijn niet altijd vrij te kiezen; afhankelijkheid, macht en veiligheid spelen mee.', counter: 'Welke verantwoordelijkheid wil je juist bewust blijven dragen?', experiment: 'Kies één verzoek waarop je niet meteen antwoordt. Zeg: “Ik kom hier later op terug.”', readHref: 'onderwerpen/boosheid.html', readTitle: 'Boosheid', readLabel: 'Lees het dossier Boosheid →', readReason: 'Deze tekst onderzoekt hoe een grenssignaal informatie kan geven, zonder iedere impuls automatisch tot juist bevel te maken.' },
        verbinden: { kicker: 'Mogelijke beweging voor vandaag', title: 'Verbinden', summary: 'Er lijkt iets te willen worden gedeeld, gevraagd of samen gedragen. Verbinding kan ook klein beginnen.', strength: 'Een ander perspectief of aanwezige ander kan isolement verzachten en nieuwe informatie geven.', friction: 'Niet iedere persoon of omgeving is veilig genoeg voor openheid.', counter: 'Wanneer beschermt alleen zijn juist iets waardevols in jou?', experiment: 'Stuur één betrouwbare persoon een eenvoudige zin: “Heb je binnenkort even tijd om te luisteren?”', readHref: 'onderwerpen/hechting.html', readTitle: 'Hechting', readLabel: 'Lees het dossier Hechting →', readReason: 'Deze tekst plaatst nabijheid naast veiligheid, autonomie, cultuur en de verschillen tussen relaties.' },
        kiezen: { kicker: 'Mogelijke beweging voor vandaag', title: 'Kiezen', summary: 'Je antwoorden blijven rond een richting of eerste stap bewegen. Misschien hoeft de keuze niet perfect te zijn om bruikbaar te worden.', strength: 'Een kleine keuze kan informatie opleveren die verder nadenken niet geeft.', friction: 'Snel beslissen is niet altijd wijs wanneer gevolgen groot of moeilijk omkeerbaar zijn.', counter: 'Welke twijfel bevat informatie die je nog werkelijk nodig hebt?', experiment: 'Maak één keuze die klein, veilig en omkeerbaar is. Behandel haar als proef, niet als eindoordeel.', readHref: 'veranderroute.html', readTitle: 'De Veranderroute', readLabel: 'Volg de bestaande Veranderroute →', readReason: 'Deze route behandelt verandering als een proef met context, terugval en kleine haalbare stappen — niet als één grote beslissing.' }
      }
    },
    {
      id: 'luisteren-of-repareren',
      title: 'Luister je nog — of heb je het al opgelost?',
      eyebrow: 'Gesprekssimulatie · helpen zonder overnemen',
      mode: 'support',
      introTitle: 'Tien gesprekken. Wat doe jij als eerste?',
      introCopy: 'Je reageert op vrienden, een partner, collega’s en familie. Iedere scène vertelt iets over timing, relatie, macht, draagkracht en veiligheid. Kies niet het mooiste antwoord, maar wat jij waarschijnlijk als eerste doet.',
      resultOrder: [],
      dimensions: {
        luisteren: { group:'skill', label:'Actief luisteren', short:'Je vertraagt, erkent en controleert of je goed begrepen hebt.', atlasHref:'onderwerpen/ervaring.html', atlasTitle:'Ervaring', atlasCopy:'Waarom jouw interpretatie en de beleving van de ander nooit volledig samenvallen.' },
        afstemmen: { group:'skill', label:'Afstemmen', short:'Je onderzoekt welke vorm van steun nu werkelijk gewenst is.', atlasHref:'onderwerpen/hechting.html', atlasTitle:'Hechting & responsiviteit', atlasCopy:'Over begrip, validatie, zorg en verschil tussen relaties.' },
        eigenaarschap: { group:'skill', label:'Eigenaarschap laten', short:'Je helpt zonder de keuze of het probleem van de ander af te pakken.', atlasHref:'onderwerpen/de-ander-verandert-je.html', atlasTitle:'De ander verandert je', atlasCopy:'Over steun, autonomie, invloed en zelfverlies.' },
        grenzen: { group:'skill', label:'Grenzen tonen', short:'Je blijft betrokken en maakt tegelijk je eigen draagkracht zichtbaar.', atlasHref:'onderwerpen/boosheid.html', atlasTitle:'Boosheid & grenzen', atlasCopy:'Over grenssignalen, verantwoordelijkheid en handelingsruimte.' },
        fixen: { group:'reflex', label:'Snel fixen', short:'Je brengt een oplossing voordat duidelijk is wat de ander nodig heeft.', atlasHref:'onderwerpen/de-ander-verandert-je.html', atlasTitle:'Steunen zonder sturen', atlasCopy:'Wanneer hulp verruimt en wanneer ze de richting van de ander kleiner maakt.' },
        overnemen: { group:'reflex', label:'Overnemen', short:'Je neemt een taak, keuze of verantwoordelijkheid uit handen.', atlasHref:'onderwerpen/de-ander-verandert-je.html', atlasTitle:'Autonomie in relaties', atlasCopy:'Nabijheid zonder dat iemand ophoudt medeauteur te zijn.' },
        pleasen: { group:'reflex', label:'Pleasen', short:'Je maakt jezelf snel beschikbaar om spanning of teleurstelling te voorkomen.', atlasHref:'onderwerpen/schaamte.html', atlasTitle:'Schaamte', atlasCopy:'Over pleasen, verbergen en de bescherming onder sociaal gedrag.' },
        terugtrekken: { group:'reflex', label:'Uit contact gaan', short:'Je zwijgt, verkleint of verplaatst het gesprek wanneer het ongemakkelijk wordt.', atlasHref:'onderwerpen/hechting.html', atlasTitle:'Nabijheid en afstand', atlasCopy:'Over zoeken, afsluiten, bevriezen en relatiespecifieke veiligheid.' }
      },
      questions: [
        { scene:'Een vriend stuurt om 22.14 uur', contextLabel:'Geen acuut gevaar · je eigen grens telt mee', contextTone:'ordinary', context:'Dit is ongewoon voor hem. Hij noemt geen gevaar en vraagt niet expliciet om advies. Jij moet morgen vroeg op.', text:'“Vandaag ging werkelijk alles mis. Ik weet zelfs niet waar ik moet beginnen.”', options:[
          s('q1-erken','“Dat klinkt alsof je helemaal op bent. Begin maar waar jij wilt.”','Je erkent eerst en laat het tempo bij de ander.',{luisteren:2,eigenaarschap:1}),
          s('q1-vraag','“Wat drukte vandaag het zwaarst?”','Je opent één duidelijke deur zonder al een richting te kiezen.',{luisteren:1,afstemmen:1}),
          s('q1-afstem','“Wil je vooral vertellen, samen ordenen of iets praktisch bekijken?”','Je vraagt welke vorm van steun gewenst is.',{afstemmen:2,eigenaarschap:1}),
          s('q1-fix','“Maak eerst een lijst van wat morgen echt moet; dan wordt het overzichtelijk.”','Je brengt structuur, maar nog vóór je weet of advies gewenst is.',{fixen:2}),
          s('q1-please','“Bel me maar. Ik blijf wakker zolang jij me nodig hebt.”','Je biedt veel beschikbaarheid; je eigen grens blijft buiten beeld.',{pleasen:2,overnemen:1}),
          s('q1-stil','Ik lees het bericht, maar antwoord voorlopig niets.','Ook stilte is gedrag; de ander weet nog niet wat ze betekent.',{terugtrekken:2})
        ]},
        { scene:'Je partner vertelt voor de derde keer over hetzelfde werkconflict', contextLabel:'Herhaling · machtsverschil op het werk', contextTone:'power', context:'De baas kleineert je partner geregeld in vergaderingen. Je partner is financieel afhankelijk van deze baan, heeft nog geen concrete hulpvraag gesteld en jij bent vanavond uitgeput.', text:'“Mijn baas deed het wéér. Ik blijf hier volledig in vastzitten.”', options:[
          s('q2-samenvat','“Je lijkt tegelijk kwaad én bang voor wat er gebeurt als je reageert. Klopt dat?”','Je vat samen en laat ruimte om je lezing te corrigeren.',{luisteren:2,afstemmen:1}),
          s('q2-eigen','“Welke opties zie je zelf, ook de opties die je nog niet durft?”','Je ondersteunt het eigen denken zonder de uitkomst te bepalen.',{eigenaarschap:2,luisteren:1}),
          s('q2-mail','“Stuur mij je mail. Ik herschrijf hem wel en dan is het opgelost.”','Je neemt een concrete taak én een deel van de positie van de ander over.',{overnemen:2,fixen:1}),
          s('q2-advies','“Je moet nu echt naar HR stappen. Dit duurt al veel te lang.”','Je advies is helder, maar de keuze ligt al bijna vast.',{fixen:2,overnemen:1}),
          s('q2-grens','“Ik wil hier morgen twintig minuten rustig bij zijn; vanavond kan ik niet meer goed luisteren.”','Je blijft betrokken en maakt je draagkracht concreet.',{grenzen:2,afstemmen:1}),
          s('q2-meegaan','“Je hebt volledig gelijk. Je baas is gewoon verschrikkelijk.”','Instemmen kan nabij voelen, maar onderzoekt niet wat werkelijk helpt.',{pleasen:1,terugtrekken:1})
        ]},
        { scene:'Je zus vraagt rechtstreeks advies', contextLabel:'Waarschuwingssignalen · mogelijk controlerend gedrag', contextTone:'warning', context:'Haar partner leest haar berichten, kleineert haar en wordt kwaad als ze zonder hem afspreekt. Ze zegt dat ze nu niet fysiek in gevaar is, maar vreest zijn reactie als ze een grens stelt of vertrekt.', text:'“Wat denk jij dat ik moet doen met mijn relatie?”', options:[
          s('q3-veilig','“Ik maak me zorgen om de controle en je angst. Voel je je vandaag veilig? We kunnen samen opties en hulp bekijken, op jouw tempo.”','Je benoemt concreet gedrag, controleert de veiligheid en laat de regie zo veel mogelijk bij haar.',{luisteren:1,afstemmen:2,eigenaarschap:2,grenzen:2}),
          s('q3-beslis','“Eerlijk? Ik vind dat je er vandaag nog een einde aan moet maken.”','Je neemt de signalen ernstig, maar bepaalt tempo en uitkomst van een mogelijk riskante keuze.',{fixen:2,overnemen:2}),
          s('q3-twijfel','“Wat maakt dat je bang bent voor zijn reactie, en wat heb jij nodig om veilig te kunnen nadenken?”','Je onderzoekt haar ervaring en brengt veiligheid in beeld zonder meteen te beslissen.',{luisteren:2,eigenaarschap:2,afstemmen:1}),
          s('q3-plan','“Zullen we op een veilige plek opschrijven wie je kunt bellen, waar je heen kunt en welke stap jij zelf wilt zetten?”','Je biedt concrete veiligheidssteun binnen een plan dat zij mee bestuurt.',{afstemmen:2,eigenaarschap:2,grenzen:1}),
          s('q3-gerust','“Iedere relatie heeft moeilijke periodes. Misschien waait dit wel over.”','Geruststelling verkleint hier concrete signalen van controle en angst.',{pleasen:1,terugtrekken:2}),
          s('q3-confronteer','“Geef mij zijn nummer. Ik zal hem wel zeggen dat dit moet stoppen.”','Je neemt het conflict over en kunt het risico vergroten zonder haar situatie of veiligheid te kennen.',{overnemen:2,fixen:2})
        ]},
        { scene:'Een collega vraagt vlak voor het einde van je werkdag', contextLabel:'Donderdag 17.20 uur · goede werkrelatie · jij hebt haast', contextTone:'power', context:'Jullie werken graag samen en hij hielp jou eerder al twee keer uit de nood. Tegelijk is dit zijn derde late verzoek deze maand. Jij bent moe, moet over tien minuten weg voor een privéafspraak en hebt morgenochtend zelf een deadline. Het team is onderbezet, maar er is geen noodgeval.', text:'“Kun jij mijn presentatie voor morgenochtend nog afwerken? Ik trek het echt niet.”', options:[
          s('q4-ja','“Natuurlijk.” Ik schrap mijn eigen avond en neem het werk over.','Je ontlast de ander onmiddellijk; de kost voor jou blijft onuitgesproken.',{pleasen:2,overnemen:2}),
          s('q4-nee','“Nee, dat lukt me niet.”','Je grens is duidelijk, maar je onderzoekt niet wat er verder nodig of mogelijk is.',{grenzen:2}),
          s('q4-samen','“Ik kan twintig minuten helpen kiezen wat echt af moet; daarna ga ik naar huis.”','Je biedt begrensde samenwerking en laat de taak bij de eigenaar.',{grenzen:2,eigenaarschap:2,afstemmen:1}),
          s('q4-doen','“Stuur maar door. Ik maak het sneller zelf.”','Efficiëntie wint; verantwoordelijkheid en leerproces verschuiven naar jou.',{overnemen:2,fixen:1}),
          s('q4-vragen','“Wat is al klaar en welk onderdeel blokkeert je precies?”','Je zoekt eerst waar gerichte steun verschil kan maken.',{luisteren:1,afstemmen:2,eigenaarschap:1}),
          s('q4-negeren','Ik zie het bericht en besluit pas morgen te antwoorden.','Je beschermt je avond zonder je grens of beschikbaarheid mee te delen.',{terugtrekken:2})
        ]},
        { scene:'Een vriend zegt tijdens een gesprek', contextLabel:'Zelftwijfel na een vernederend moment', contextTone:'ordinary', context:'Hij vertelde net dat vrienden hem uitlachten toen hij een grens aangaf. Dit is de eerste keer dat hij erover praat en hij heeft nog niet gezegd welke reactie hij van jou hoopt.', text:'“Misschien stel ik me gewoon aan.”', options:[
          s('q5-check','“Ik hoor dat je aan jezelf twijfelt. Wat maakt dat je het aanstellen noemt?”','Je erkent de twijfel en onderzoekt haar betekenis.',{luisteren:2,eigenaarschap:1}),
          s('q5-nee','“Nee joh, natuurlijk stel je je niet aan.”','Je wilt geruststellen, maar vult snel in wat de ervaring betekent.',{fixen:1,pleasen:1}),
          s('q5-klopt','“Misschien maak je het inderdaad wat groter dan het is.”','Je verkleint de ervaring voordat je haar hebt onderzocht.',{terugtrekken:2}),
          s('q5-mij','“Dat heb ik ook gehad. Bij mij was het zelfs nog erger…”','Je zoekt herkenning, maar verplaatst het middelpunt van het gesprek.',{terugtrekken:1}),
          s('q5-nodig','“Wat zou nu het meest helpen: erkenning, een eerlijke tegenstem of samen uitzoeken?”','Je maakt verschillende vormen van steun bespreekbaar.',{afstemmen:2,luisteren:1}),
          s('q5-diep','“Kom, we gaan zitten. Vertel me vanaf het begin wat er precies gebeurde en waarom dit je zo raakt.”','Je biedt veel aandacht en trekt het gesprek meteen de diepte in. Dat kan betrokken voelen, maar de ander koos nog niet of dit het juiste moment of tempo is.',{luisteren:1,overnemen:1,pleasen:1})
        ]},
        { scene:'Na een avond samen uit wil een vriend zelf rijden', contextLabel:'Acuut gevaar · ongeveer zes drankjes · jij bent nuchter', contextTone:'urgent', context:'Jullie gingen samen naar een verjaardag, maar kwamen elk met een eigen auto. In vier uur zag je hem ongeveer zes alcoholische drankjes drinken. Hij praat onduidelijk, wankelt, heeft zijn autosleutels vast en wil nu vertrekken. Jij dronk alcoholvrij en er zijn andere mensen in de buurt die kunnen helpen.', text:'“Ik rijd zelf wel naar huis. Bemoei je er niet mee.”', options:[
          s('q6-meerijden','“Ik laat je niet rijden. Ik regel een taxi of breng je thuis; jij kiest welke van de twee.”','Bij acuut risico mag steun directer zijn; je laat nog keuze binnen veilige opties.',{afstemmen:1,eigenaarschap:1,grenzen:2}),
          s('q6-sleutels','Ik pak zonder iets te zeggen de autosleutels af en beslis wat er gebeurt.','Je grijpt in voor veiligheid, maar zonder uitleg of resterende keuze.',{overnemen:1,grenzen:1}),
          s('q6-advies','“Dat lijkt me geen goed idee, maar je moet het zelf weten.”','Je benoemt het risico maar laat de onveilige handeling ongemoeid.',{terugtrekken:2}),
          s('q6-rustig','“Waarom wil je per se zelf rijden? Vertel eerst eens wat er speelt.”','Luisteren kan informatie geven, maar het onmiddellijke risico vraagt óók begrenzing.',{luisteren:1,terugtrekken:1}),
          s('q6-pleasen','“Oké, als jij echt denkt dat het kan.”','Harmonie bewaren krijgt voorrang op een concreet veiligheidsrisico.',{pleasen:2,terugtrekken:1}),
          s('q6-hulp','Ik schakel er iemand bij in en blijf tot er veilig vervoer is.','Je deelt de verantwoordelijkheid en blijft bij een concreet veiligheidsdoel.',{grenzen:2,afstemmen:1})
        ]},
        { scene:'Een medewerker spreekt je na het teamoverleg aan', contextLabel:'Jij bent leidinggevende · structurele werkdruk · weinig tijd', contextTone:'power', context:'Jij verdeelt het werk en beoordeelt deze medewerker. Door een open vacature werkt die al zes weken bijna elke avond langer. Jullie contact is goed. Over vijftien minuten begint jouw volgende vergadering; er is geen acuut medisch gevaar.', text:'“Ik kan dit tempo echt niet blijven volhouden.”', options:[
          s('q7-verantwoord','“Dank dat je dit zegt. Deze werkdruk is ook mijn verantwoordelijkheid. Wat moet vandaag stoppen, en wanneer plannen we hier rustig tijd voor?”','Je erkent het machtsverschil, neemt je structurele verantwoordelijkheid en betrekt de medewerker bij de eerstvolgende stap.',{luisteren:1,afstemmen:2,grenzen:2,eigenaarschap:1}),
          s('q7-luister','“Waar loopt de druk voor jou het meest op? Ik wil eerst begrijpen wat er precies gebeurt.”','Je onderzoekt de ervaring, maar een luisterend gesprek moet hier nog gevolgd worden door handelen binnen jouw rol.',{luisteren:2,afstemmen:1}),
          s('q7-time','“Misschien moeten we eens naar je planning en timemanagement kijken.”','Je maakt een structureel capaciteitsprobleem snel tot een vaardigheidsprobleem van de medewerker.',{fixen:2,terugtrekken:1}),
          s('q7-overneem','“Geef mij je zwaarste dossier. Ik werk het vanavond zelf af.”','Je biedt directe verlichting, maar maakt overwerk afhankelijk van jouw persoonlijke reddingsactie.',{overnemen:2,pleasen:1}),
          s('q7-motiveer','“Nog even doorbijten; zodra de vacature ingevuld is, wordt het beter.”','Je probeert moed te geven, maar laat de huidige grens en jouw invloed op het systeem onbesproken.',{pleasen:1,terugtrekken:2}),
          s('q7-later','“Stuur me volgende week een mail, dan zoeken we een moment.”','Je verplaatst een terugkerend signaal terwijl jij juist meer macht hebt om nu ruimte te maken.',{terugtrekken:2})
        ]},
        { scene:'Een goede vriend vraagt je om een bericht te schrijven', contextLabel:'Twee weken na een breuk · expliciete hulpvraag · geen onveiligheid', contextTone:'ordinary', context:'Na een relatie van vier jaar zijn ze rustig uit elkaar gegaan. Er waren geen signalen van dwang of geweld. De ex vroeg een week geen contact. Jij kent hen allebei, maar bent vooral bevriend met je vriend. Je hebt vanavond tijd en bent kalm.', text:'“Schrijf jij wat ik moet sturen? Ik maak het alleen maar erger.”', options:[
          s('q8-vraag','“Wat wil je dat je bericht eerlijk zegt, en wat wil je zelf absoluut niet beloven?”','Je helpt zijn eigen bedoeling en grens scherper te krijgen voordat er woorden komen.',{luisteren:1,eigenaarschap:2}),
          s('q8-samen','“Jij maakt een eerste versie; daarna kijk ik mee of ze duidelijk en respectvol is.”','Je biedt concrete steun terwijl de eerste stem en verantwoordelijkheid bij hem blijven.',{afstemmen:2,eigenaarschap:2}),
          s('q8-schrijven','“Geef je telefoon maar. Ik weet precies wat je moet zeggen.”','De hulp is gevraagd, maar jij neemt inhoud, toon en mogelijk ook de gevolgen volledig over.',{overnemen:2,fixen:1}),
          s('q8-wacht','“Ik denk dat geen bericht sturen tijdens die afgesproken week nu het meest respectvol is. Wil je horen waarom?”','Je geeft duidelijk advies én vraagt ruimte om je reden te bespreken, maar stuurt wel naar één uitkomst.',{grenzen:1,afstemmen:1,fixen:1}),
          s('q8-gerust','“Wat je ook stuurt, als de liefde echt is komt het wel goed.”','Je stelt gerust zonder rekening te houden met de afgesproken ruimte of de werkelijke gevolgen.',{pleasen:2}),
          s('q8-weg','“Relatieberichten zijn niet mijn ding.” Ik laat het gesprek daar eindigen.','Je bewaakt een mogelijke grens, maar maakt niet duidelijk of je op een andere manier aanwezig kunt zijn.',{terugtrekken:2,grenzen:1})
        ]},
        { scene:'Je partner wil na een conflict niet verder praten', contextLabel:'Zondagmiddag · veilige relatie · jullie hebben allebei tijd', contextTone:'ordinary', context:'Jullie verhieven net allebei je stem over de verdeling van het huishouden, zonder dreiging, schelden of geweld. Je partner heeft meestal een halfuur nodig om te kalmeren; stilte maakt jou juist onrustig. Er zijn vandaag geen andere afspraken.', text:'“Ik wil hier nu niet verder over praten.”', options:[
          s('q9-pauze','“Oké. Zullen we een halfuur pauze nemen en om vier uur opnieuw proberen?”','Je respecteert de gevraagde ruimte en maakt tegelijk duidelijk wanneer het contact wordt hervat.',{afstemmen:2,grenzen:1,eigenaarschap:1}),
          s('q9-check','“Wil je alleen even rust, of wil je dit onderwerp vandaag helemaal niet meer openen?”','Je vraagt wat de grens precies betekent zonder haar meteen te bestrijden.',{luisteren:1,afstemmen:2}),
          s('q9-duwen','“Nee, we praten dit nu uit. Weglopen maakt het alleen erger.”','Je onrust bepaalt het tempo en overschrijft de expliciete vraag om een pauze.',{overnemen:2,fixen:1}),
          s('q9-cadeau','Ik bestel iets lekkers en doe extra lief, zodat de sfeer weer goed wordt zonder het onderwerp terug te nemen.','Je probeert de verbinding te herstellen, maar harmonie vervangt het onopgeloste gesprek.',{pleasen:2,terugtrekken:1}),
          s('q9-stil','Ik zeg niets meer en wacht af tot mijn partner ooit zelf opnieuw begint.','Je geeft ruimte, maar maakt de duur en gedeelde verantwoordelijkheid volledig onduidelijk.',{terugtrekken:2}),
          s('q9-analyse','“Laten we eerst precies uitzoeken waarom jij bij conflict altijd dichtklapt.”','Je maakt van een concrete pauze meteen een diep patroononderzoek waar niet om gevraagd is.',{overnemen:1,fixen:1})
        ]},
        { scene:'Je moeder reageert gekwetst op je agenda', contextLabel:'Warme band · terugkerende schuld · jouw draagkracht is laag', contextTone:'power', context:'Je belt haar wekelijks en bezocht haar twee weken geleden. Ze mist gezelschap, maar heeft ook vrienden, vervoer en een kaartclub. Jij combineert een drukke baan met twee jonge kinderen en bent deze maand erg moe. In jullie familie weegt voor elkaar zorgen zwaar.', text:'“Blijkbaar is je werk belangrijker dan je eigen moeder.”', options:[
          s('q10-beide','“Ik hoor dat je me mist. Ik wil je zien én ik kan deze week niet langskomen. Zullen we nu iets haalbaars plannen?”','Je erkent haar gemis zonder de beschuldiging als volledige opdracht over te nemen.',{luisteren:1,grenzen:2,afstemmen:2}),
          s('q10-vraag','“Vraag je me om vaker te komen, of wil je vooral vertellen hoe alleen je je de laatste tijd voelt?”','Je maakt de behoefte achter de pijnlijke formulering bespreekbaar.',{luisteren:2,afstemmen:2}),
          s('q10-beloven','“Het spijt me. Ik kom vanaf nu iedere zondag, beloofd.”','Je probeert de schuld en spanning onmiddellijk te stoppen met een grote belofte.',{pleasen:2,overnemen:1}),
          s('q10-oplossen','“Ik zoek wel nieuwe activiteiten voor je en zet ze meteen in je agenda.”','Je reageert op een relationeel verlangen met een plan dat haar sociale leven bestuurt.',{fixen:2,overnemen:1}),
          s('q10-verwijt','“Je hebt genoeg mensen om je heen. Het is niet mijn taak om je bezig te houden.”','Je benoemt verantwoordelijkheid, maar doet dat op een manier die haar emotie en jullie band afsnijdt.',{terugtrekken:2,grenzen:1}),
          s('q10-negeren','Ik reageer niet op die zin en stuur de volgende dag een foto van de kinderen.','Je houdt contact, maar ontwijkt zowel het gemis als de druk die haar woorden op jou zetten.',{terugtrekken:2,pleasen:1})
        ]}
      ]
    },
    {
      id: 'waar-komt-je-ja-vandaan',
      title: 'Waar komt jouw ja vandaan?',
      eyebrow: 'Keuzes · motivatie',
      mode: 'path',
      resultOrder: ['volmondig', 'harmonie', 'verantwoordelijkheid', 'automatisch', 'voorlopig'],
      questions: [
        { text: 'Iemand vraagt je iets onverwachts. Wat gebeurt er meestal eerst?', options: o(['Ik voel vrij snel echte zin of geen zin.', 'volmondig'], ['Ik kijk wat mijn antwoord met de ander zal doen.', 'harmonie'], ['Ik denk na over wat van mij verwacht mag worden.', 'verantwoordelijkheid'], ['Ik hoor mezelf al ja zeggen voordat ik heb nagedacht.', 'automatisch'], ['Ik wil eerst wat meer informatie of tijd.', 'voorlopig']) },
        { text: 'Hoe voelt een ja achteraf meestal in je lichaam?', options: o(['Ruim en energiek.', 'volmondig'], ['Rustig omdat de relatie goed blijft.', 'harmonie'], ['Stevig omdat ik deed wat nodig was.', 'verantwoordelijkheid'], ['Zwaarder dan ik tijdens het antwoorden merkte.', 'automatisch'], ['Nog open: ik blijf voelen of het echt past.', 'voorlopig']) },
        { text: 'Welke zin is voor jou het moeilijkst?', options: o(['“Dit wil ik echt niet.”', 'volmondig'], ['“Je zult dit misschien jammer vinden, maar…”', 'harmonie'], ['“Dit is niet mijn verantwoordelijkheid.”', 'verantwoordelijkheid'], ['“Ik wil eerst nadenken voordat ik antwoord.”', 'automatisch'], ['“Mijn antwoord is voorlopig, niet definitief.”', 'voorlopig']) },
        { text: 'Wat maakt een ja voor jou het meest betekenisvol?', options: o(['Dat het van binnenuit klopt.', 'volmondig'], ['Dat het verbinding of samenwerking beschermt.', 'harmonie'], ['Dat ik betrouwbaar ben en iets draag wat ertoe doet.', 'verantwoordelijkheid'], ['Dat ik snel beschikbaar en behulpzaam kan zijn.', 'automatisch'], ['Dat er ruimte blijft om onderweg bij te sturen.', 'voorlopig']) },
        { text: 'Wanneer merk je meestal dat een ja niet goed paste?', options: o(['Als mijn aanvankelijke energie snel verdwijnt.', 'volmondig'], ['Als ik wrevel voel tegenover degene voor wie ik het deed.', 'harmonie'], ['Als plicht alle andere grenzen verdringt.', 'verantwoordelijkheid'], ['Als mijn lichaam pas later protesteert.', 'automatisch'], ['Als onduidelijkheid te lang blijft aanslepen.', 'voorlopig']) },
        { text: 'Welke kleine verandering zou jouw ja eerlijker maken?', options: o(['Vaker hardop zeggen waar ik werkelijk zin in heb.', 'volmondig'], ['Teleurstelling niet meteen als relatiebreuk zien.', 'harmonie'], ['Verschil maken tussen verantwoordelijkheid en oververantwoordelijkheid.', 'verantwoordelijkheid'], ['Een standaardpauze nemen vóór ik antwoord.', 'automatisch'], ['Duidelijk zeggen wanneer ik opnieuw beslis.', 'voorlopig']) }
      ],
      results: {
        volmondig: { kicker: 'De sterkste lijn in je antwoorden', title: 'Het volmondige ja', summary: 'Je zoekt naar een ja dat van binnenuit gedragen voelt. Zin, betekenis en persoonlijke instemming wegen zwaar.', strength: 'Een zelfgedragen keuze kan energie en helderheid geven.', friction: 'Niet alles wat waardevol is voelt onmiddellijk aantrekkelijk; zorg en inzet kunnen ook moeite kosten.', counter: 'Wanneer ontstaat betrokkenheid pas nadat je begonnen bent?', experiment: 'Noem bij je volgende ja één concrete reden waarom jij dit zelf wilt.', readHref: 'onderwerpen/persoonlijkheid.html', readTitle: 'Persoonlijkheid', readLabel: 'Lees het dossier Persoonlijkheid →', readReason: 'Deze tekst plaatst persoonlijke waarden naast gewoonten, context en veranderlijke rollen — zodat “van binnenuit” niet het enige verhaal wordt.' },
        harmonie: { kicker: 'De sterkste lijn in je antwoorden', title: 'Het harmonieja', summary: 'Je antwoord houdt sterk rekening met verbinding, sfeer en de mogelijke teleurstelling van anderen.', strength: 'Afstemming en zorg voor relaties zijn echte menselijke waarden, geen zwakte.', friction: 'Een relatie kan uiterlijk rustig blijven terwijl jij innerlijk steeds minder ruimte ervaart.', counter: 'Welke relatie kan een eerlijk nee waarschijnlijk beter dragen dan je vreest?', experiment: 'Oefen één vriendelijke grenszin: “Ik wil helpen, maar dit lukt me nu niet.”', readHref: 'onderwerpen/de-ander-verandert-je.html', readTitle: 'De ander verandert je', readLabel: 'Lees het dossier De ander verandert je →', readReason: 'Deze tekst onderzoekt afstemming, steun en zelfverlies zonder zorg voor relaties als zwakte weg te zetten.' },
        verantwoordelijkheid: { kicker: 'De sterkste lijn in je antwoorden', title: 'Het verantwoordelijke ja', summary: 'Je ja lijkt vaak verbonden met betrouwbaarheid, plicht en wat volgens jou werkelijk gedragen moet worden.', strength: 'Verantwoordelijkheid kan anderen veiligheid en continuïteit geven.', friction: 'Wie veel kan dragen, krijgt soms ook te veel toegeschoven — of schuift het zichzelf toe.', counter: 'Welke taak is belangrijk, maar hoeft niet noodzakelijk door jou te worden gedaan?', experiment: 'Vraag bij één taak: “Ben ik verantwoordelijk, betrokken of alleen beschikbaar?”', readHref: 'onderwerpen/hechting.html', readTitle: 'Hechting', readLabel: 'Lees het dossier Hechting →', readReason: 'Deze tekst laat zien hoe zorg, afhankelijkheid, veiligheid en verantwoordelijkheid tussen relaties kunnen verschillen.' },
        automatisch: { kicker: 'De sterkste lijn in je antwoorden', title: 'Het snelle ja', summary: 'Je antwoord is soms al vertrokken voordat je wensen, grenzen of beschikbare energie volledig zijn ingehaald.', strength: 'Spontane bereidheid kan warm, gul en daadkrachtig zijn.', friction: 'Een snel ja kan later veranderen in vermoeidheid, uitstel of stille wrevel.', counter: 'Wanneer is jouw snelheid juist een betrouwbare vorm van intuïtie?', experiment: 'Gebruik vandaag één standaardzin: “Ik kijk even of het past en laat het je weten.”', readHref: 'onderwerpen/gewoontes.html', readTitle: 'Gewoontes', readLabel: 'Lees het dossier Gewoontes →', readReason: 'Deze tekst onderzoekt automatische reacties zonder ze te reduceren tot karakter of een eenvoudig gebrek aan wilskracht.' },
        voorlopig: { kicker: 'De sterkste lijn in je antwoorden', title: 'Het voorlopige ja', summary: 'Je houdt graag ruimte om te onderzoeken, informatie te verzamelen of later bij te sturen.', strength: 'Voorlopigheid kan nuance en leervermogen beschermen.', friction: 'Een open antwoord kan voor jou veilig voelen maar voor anderen lang onduidelijk blijven.', counter: 'Wanneer weet je eigenlijk al genoeg om een richting te kiezen?', experiment: 'Koppel aan één voorlopig antwoord een helder moment: “Morgen om vier uur beslis ik.”', readHref: 'veranderroute.html', readTitle: 'De Veranderroute', readLabel: 'Volg de bestaande Veranderroute →', readReason: 'Deze route laat zien hoe je een richting als kleine proef kunt behandelen, met ruimte om bij te sturen.' }
      }
    },
    {
      id: 'wie-zit-aan-het-stuur',
      title: 'Wie heeft vandaag de autosleutels?',
      eyebrow: 'Psychologische afstand · tijdelijke bezetting',
      mode: 'ranking',
      customEyebrow: 'Stuurtafel · één situatie, vier reacties',
      customTitle: 'Zet geen mensen in de auto. Zet zinnen op een stoel.',
      customIntro: 'Iedere kaart reageert op precies dezelfde rit. Schrijf wat die reactie in jou zegt en verdeel daarna hoeveel invloed ze vandaag krijgt.',
      customMissLabel: 'Mijn innerlijke wagenpark heeft ander personeel',
      customMissHelp: 'Ook geldig. Een metafoor moet jou helpen; jij hoeft niet in de metafoor te passen.',
      rankSeats: [
        { label: 'Aan het stuur', help: 'Deze zin bepaalt waarschijnlijk wat je doet als je niets bijstuurt.', weight: 4 },
        { label: 'Copiloot', help: 'Deze zin bevat informatie die je bewust wilt meenemen.', weight: 3 },
        { label: 'Achterbank · links', help: 'Mag gehoord worden, maar beslist niet over je volgende stap.', weight: 2 },
        { label: 'Achterbank · rechts', help: 'Ook aanwezig — zonder toegang tot pedalen of claxon.', weight: 1 }
      ],
      gameOptions: [
        { result: 'motor', symbol: '⚙', label: 'De Reflex', copy: 'Wil snel handelen, vermijden, pleasen, fixen of bevriezen.', prompt: 'Wat wil je onmiddellijk doen, zeggen of juist vermijden?', placeholder: 'Ik wil nu meteen…' },
        { result: 'situatielezer', symbol: '◎', label: 'De Relatieradar', copy: 'Scant reacties, verwachtingen, macht en mogelijke teleurstelling.', prompt: 'Met wiens reactie houd je rekening — en wat probeer je daar te regelen?', placeholder: 'Ik probeer te voorkomen dat…' },
        { result: 'verhalenmaker', symbol: '!', label: 'De Alarmcentrale', copy: 'Maakt een risico groot genoeg om er zeker niet overheen te kijken.', prompt: 'Waarvoor probeert deze stem je te waarschuwen of beschermen?', placeholder: 'Pas op, want anders…' },
        { result: 'kompasdrager', symbol: '◇', label: 'Het Kompas', copy: 'Kijkt voorbij de opluchting van nu naar wat belangrijk blijft.', prompt: 'Wat wil je belangrijk vinden in hoe je hiermee omgaat?', placeholder: 'Ook als dit lastig is, wil ik…' }
      ],
      theoryHref: 'onderwerpen/persoonlijkheid.html',
      theoryLabel: 'Waarom je persoonlijkheid rijker is dan één type →',
      resultOrder: ['motor', 'situatielezer', 'kompasdrager', 'verhalenmaker'],
      questions: [
        { text: 'Je stapt een kamer binnen waar je bijna niemand kent. Waar begint jouw gedrag meestal?', options: o(['Bij een vertrouwde neiging: ik kijk eerst, of ik stap juist meteen op iemand af.', 'motor'], ['Bij de kamer zelf: wie is er, hoe veilig voelt het en wat lijkt hier passend?', 'situatielezer'], ['Bij mijn bedoeling: waarvoor ben ik hier en wat wil ik niet uit het oog verliezen?', 'kompasdrager'], ['Bij de rol waarin ik mezelf daar voel belanden: nieuwkomer, helper, buitenstaander of gangmaker.', 'verhalenmaker']) },
        { text: 'Je zorgvuldig gemaakte plan valt op dinsdag om 10.17 uur uit elkaar. Wat neemt als eerste over?', options: o(['Ik lees opnieuw wat dit moment nu van me vraagt.', 'situatielezer'], ['Ik val terug op mijn bekende ritme — nuttig of lichtelijk voorspelbaar.', 'motor'], ['Ik vraag welke richting nog altijd belangrijk is, ook zonder het oorspronkelijke plan.', 'kompasdrager'], ['Mijn hoofd maakt er meteen een hoofdstuk van: “Natuurlijk gebeurt dit weer” of “Dit wordt een goed verhaal.”', 'verhalenmaker']) },
        { text: 'Iemand zegt: “Dat is zó typisch jij.” Welke reactie zit het dichtst in de buurt?', options: o(['“Bij jou misschien. In een andere omgeving ben ik heel anders.”', 'situatielezer'], ['“Ja, dat patroon is ondertussen vrij goed gedocumenteerd.”', 'motor'], ['“Hopelijk zie je daarin ook wat ik belangrijk probeer te vinden.”', 'kompasdrager'], ['“Welke versie van mij bedoel je precies? Er zijn meerdere seizoenen.”', 'verhalenmaker']) },
        { text: 'Bij een lastige keuze, welke vraag trekt het hardst aan je mouw?', options: o(['Wat wil ik dat deze keuze zegt over waar ik voor sta?', 'kompasdrager'], ['Wat doe ik in dit soort situaties doorgaans?', 'motor'], ['Wat is hier werkelijk mogelijk, met deze mensen en deze omstandigheden?', 'situatielezer'], ['Welk oud verhaal herhaal ik — en welk verhaal wil ik misschien herzien?', 'verhalenmaker']) },
        { text: 'Je wilt iets aan jezelf veranderen. Waar krijg je het meeste vertrouwen van?', options: o(['Een kleine gewoonte die ik vaak genoeg kan herhalen.', 'motor'], ['Een omgeving bouwen waarin het nieuwe gedrag meer kans krijgt.', 'situatielezer'], ['Een reden die belangrijk genoeg is om moeite voor te doen.', 'kompasdrager'], ['Een ander verhaal over wie ik al ben en nog aan het worden ben.', 'verhalenmaker']) },
        { text: 'Een oude bekende ziet je na tien jaar terug. Wat hoop je stiekem dat die opmerkt?', options: o(['Dat de herkenbare kern er nog is, alleen iets beter afgesteld.', 'motor'], ['Dat ik in nieuwe werelden ook nieuwe kanten heb leren gebruiken.', 'situatielezer'], ['Dat mijn keuzes duidelijker laten zien wat ik belangrijk vind.', 'kompasdrager'], ['Dat ik niet meer volledig woon in het verhaal dat die persoon van mij kende.', 'verhalenmaker']) },
        { text: 'Wat ergert je het meest aan een slechte persoonlijkheidstest?', options: o(['Dat één losse vraag moet bewijzen hoe ik “altijd” ben.', 'motor'], ['Dat de situatie nergens mag meedoen.', 'situatielezer'], ['Dat gedrag wordt verward met de reden waarom ik iets doe.', 'kompasdrager'], ['Dat een leuke titel plots mijn hele identiteit gijzelt.', 'verhalenmaker']) },
        { text: 'Als jouw tijdelijke hoofdrolspeler vandaag een naamkaartje kreeg, wat zou erop staan?', options: o(['De Vaste Motor — herkenbaar, herhaalbaar en soms toe aan een andere versnelling.', 'motor'], ['De Situatielezer — voelt de kamer voordat de kamer zichzelf begrijpt.', 'situatielezer'], ['De Kompasdrager — wil weten waar dit alles eigenlijk naartoe mag.', 'kompasdrager'], ['De Verhalenmaker — leeft én verzorgt ondertussen de voice-over.', 'verhalenmaker']) }
      ],
      results: {
        motor: { kicker: 'Vandaag de meeste spreektijd', title: 'De Vaste Motor', summary: 'In je antwoorden begon persoonlijkheid vaak bij wat zich herhaalt: vertrouwde voorkeuren, gewoonten en manieren van reageren. Dat patroon kan herkenbaar zijn zonder je hele verklaring te zijn.', strength: 'Een snelle reflex kan beschermen, tijd winnen of je uit een vastgelopen situatie krijgen.', friction: 'Wat vaak gebeurt, kan vanzelf gaan voelen alsof het niet anders kán — terwijl context en oefening soms meer ruimte geven.', counter: 'In welke situatie verras je jezelf juist en gedraag je je opvallend anders?', experiment: 'Kies één herkenbaar patroon en noteer drie momenten: wanneer verschijnt het, wanneer niet en wat was er anders?', readHref: 'onderwerpen/gewoontes.html', readTitle: 'Gewoontes', readLabel: 'Lees het dossier Gewoontes →', readReason: 'Deze tekst onderzoekt hoe herhaling en context een vaste motor kunnen bouwen, zonder gewoonte gelijk te stellen aan identiteit.' },
        situatielezer: { kicker: 'Vandaag de meeste spreektijd', title: 'De Situatielezer', summary: 'Je antwoorden gaven veel gewicht aan de kamer, de mensen en de werkelijke omstandigheden. Je ziet persoonlijkheid niet los van waar en met wie gedrag verschijnt.', strength: 'Een relatieradar kan macht, stemming, wederkerigheid en echte gevolgen opmerken die individueel advies gemakkelijk mist.', friction: 'Wie de kamer heel goed leest, kan het eigen signaal soms pas laat horen — of achteraf niet weten wat nu werkelijk van zichzelf kwam.', counter: 'Welke waarde of grens wil je meenemen, ook wanneer de omgeving iets anders beloont?', experiment: 'Vergelijk één terugkerend gedrag in twee situaties. Welke persoon, verwachting of mate van veiligheid verandert het?', readHref: 'onderwerpen/persoonlijkheid.html', readTitle: 'Persoonlijkheid', readLabel: 'Lees het dossier Persoonlijkheid →', readReason: 'Deze tekst verdiept waarom gedrag per situatie kan wisselen en brede trekken toch enige samenhang kunnen tonen.' },
        kompasdrager: { kicker: 'Vandaag de meeste spreektijd', title: 'De Kompasdrager', summary: 'In je antwoorden kregen doelen, waarden en redenen veel invloed. Voor jou wordt persoonlijkheid vooral zichtbaar in de richting die iemand probeert te kiezen.', strength: 'Een kompas kan samenhang geven wanneer stemming en omstandigheden wisselen.', friction: 'Een mooie richting kan draagkracht, gewoonte of echte beperkingen onderschatten. Waarden vertellen niet automatisch welke stap nu haalbaar is.', counter: 'Wanneer deed je iets waardevols zonder dat het vooraf als een bewuste waarde voelde?', experiment: 'Maak één keuzezin af: “Dit is voor mij belangrijk, en de kleinste haalbare vorm ervan is…”', readHref: 'onderwerpen/persoonlijkheid.html', readTitle: 'Persoonlijkheid', readLabel: 'Lees het dossier Persoonlijkheid →', readReason: 'Deze tekst zet waarden en doelen naast trekken, context en levensverhaal, zodat één mooi kompas niet alles hoeft te verklaren.' },
        verhalenmaker: { kicker: 'Vandaag de meeste spreektijd', title: 'De Verhalenmaker', summary: 'Je antwoorden gingen vaak naar rollen, hoofdstukken en de betekenis die je aan verandering geeft. Je kijkt niet alleen naar wat je doet, maar ook naar wie je daardoor denkt te zijn.', strength: 'Een alarmreactie kan risico’s, grenzen en kwetsbaarheid zichtbaar maken voordat je er achteloos overheen stapt.', friction: 'Een alarm is gemaakt om aandacht te trekken, niet om kansen objectief te berekenen. Het kan een mogelijkheid laten klinken als een zekerheid.', counter: 'Welke recente gebeurtenis past verrassend slecht in het verhaal dat je meestal over jezelf vertelt?', experiment: 'Schrijf één vaste zelfzin op en voeg toe: “Behalve wanneer…” Laat minstens twee echte uitzonderingen binnen.', readHref: 'onderwerpen/persoonlijkheid.html', readTitle: 'Persoonlijkheid', readLabel: 'Lees het dossier Persoonlijkheid →', readReason: 'Deze tekst behandelt narratieve identiteit als één laag van persoonlijkheid — betekenisvol, maar nooit de volledige opname.' }
      }
    }
  ];
})();
