(function () {
  const app = document.querySelector('[data-steering-app]');
  const scene = document.querySelector('[data-game-scene]');
  if (!app || !scene) return;

  const STORAGE_KEY = 'onwijze-steering-game-v1';
  const LEGACY_KEY = 'quizkast-progress-v1';
  const phaseOrder = ['crossroads', 'voices', 'cargo', 'positions', 'council', 'trial', 'report'];
  const PHASES = {
    crossroads:{title:'Het kruispunt',transition:'Iedere rit begint ergens. Kies één concreet kruispunt waar verschillende reacties aan je trekken.'},
    voices:{title:'De passagiers melden zich',transition:'Je kruispunt ligt op tafel. Nu luisteren we naar iedere stem afzonderlijk, zonder meteen te beslissen wie gelijk heeft.'},
    cargo:{title:'Iedere passagier brengt iets mee',transition:'De stemmen hebben gesproken. Nu onderzoeken we kort wat iedere stem probeert mee te nemen in de auto.'},
    positions:{title:'Wie zit waar?',transition:'We weten wat de stemmen zeggen en beschermen. Tijd om te kijken wie momenteel waar zit.'},
    council:{title:'De Binnenraad',transition:'De huidige bezetting is zichtbaar. Twee stemmen krijgen even de ruimte om naar elkaar te luisteren.'},
    trial:{title:'De testrit',transition:'De stemmen hoeven het niet over alles eens te worden. Alleen de eerstvolgende kilometer moet klein genoeg zijn.'},
    report:{title:'Het ritverslag',transition:'De testrit ligt klaar. Bekijk je huidige auto en je tijdelijke opstelling naast elkaar.'}
  };
  const VOICES = {
    reflex:{id:'reflex',name:'De Reflex',shortName:'Reflex',description:'Wil onmiddellijk handelen, vermijden, herstellen, controleren of ingrijpen.',symbol:'↯',colorToken:'reflex',iconKey:'reflex',question:'Als je onmiddellijk moest reageren, wat zou je dan doen?',options:['Eropaf gaan','Afstand nemen','Toegeven','Mezelf verdedigen','Het snel oplossen','Uitstellen','Controleren','Niets meer zeggen','Iets anders','Ik weet het nog niet'],follow:'Maak de zin af: “Doe dit nu, want anders…”',placeholder:'Doe dit nu, want anders…'},
    relationRadar:{id:'relationRadar',name:'De Relatieradar',shortName:'Relatieradar',description:'Let op verbinding, andere mensen, verwachtingen en mogelijke reacties.',symbol:'◎',colorToken:'relation',iconKey:'relation-radar',question:'Met wie houd je in deze situatie rekening?',options:['Ik wil rekening houden met die persoon omdat …','Ik ben bang dat die persoon …','Ik denk dat die persoon van mij verwacht dat …','Ik wil onze verbinding beschermen door …','Ik weet eigenlijk niet wat die persoon denkt.','Ik weet het nog niet.'],follow:'Maak de gekozen zin eventueel verder af.',placeholder:'Wat wil deze relationele blik toevoegen?'},
    compass:{id:'compass',name:'Het Kompas',shortName:'Kompas',description:'Kijkt naar je waarden, grenzen en de manier waarop je wilt handelen.',symbol:'◇',colorToken:'compass',iconKey:'compass',question:'Wat wil je in deze situatie niet verliezen?',options:['Eerlijkheid','Vrijheid','Veiligheid','Verbinding','Zelfrespect','Zorg','Rechtvaardigheid','Rust','Nieuwsgierigheid','Iets anders','Ik weet het nog niet'],follow:'Hoe zou je willen handelen, ook als de uitkomst onzeker blijft?',placeholder:'Een waarde is een richting, geen garantie op een uitkomst.'},
    storyMaker:{id:'storyMaker',name:'De Verhalenmaker',shortName:'Verhalenmaker',description:'Zoekt betekenis en vormt verhalen over jou, de ander en wat er mogelijk zal gebeuren.',symbol:'⋯',colorToken:'story',iconKey:'story-maker',question:'Welke zin wil je hoofd afmaken?',options:['Dit zegt over mij dat …','Dit zegt over de ander dat …','Als dit zo verdergaat, dan …'],follow:'Waar lijkt dit verhaal momenteel het meest op?',placeholder:'Maak minstens één zin af.'}
  };
  const voiceIds = Object.keys(VOICES);
  const POSITIONS = {
    driver:{id:'driver',name:'Aan het stuur',help:'Bepaalt momenteel grotendeels wat ik doe.'},
    front:{id:'front',name:'Voorin',help:'Praat sterk mee en beïnvloedt mijn richting.'},
    back:{id:'back',name:'Achterin',help:'Is aanwezig, maar krijgt minder invloed.'},
    outside:{id:'outside',name:'Buiten de auto',help:'Krijgt momenteel nauwelijks ruimte.'}
  };
  const protections = ['Veiligheid','Verbinding','Waardigheid','Controle','Vrijheid','Zekerheid','Rust','Erkenning','Rechtvaardigheid','Toekomstmogelijkheden','Iets anders','Weet ik nog niet'];
  const influences = ['Veel invloed','Redelijk wat invloed','Weinig invloed','Nauwelijks invloed','Weet ik nog niet'];
  const trialOptions = ['Eerst extra informatie zoeken','Eén nacht wachten','Een korte vraag stellen','Een grens benoemen','Iets kleins uitproberen','Steun vragen','Een keuze tijdelijk testen','Bewust nog niet beslissen','Een andere kleine stap','Ik weet het nog niet'];
  const reviewOptions = ['Later vandaag','Morgen','Binnen enkele dagen','Na een bepaald gesprek of moment','Ik hoef hier geen moment voor vast te leggen','Weet ik nog niet'];

  function emptyVoice() { return {visited:false,recognized:null,response:'',responseOption:'',other:'',protection:'',influence:'',currentPosition:'',trialPosition:''}; }
  function emptyState() {
    return {version:1,currentPhase:'start',voiceIndex:0,situation:{description:'',dilemma:'',deadline:''},voices:Object.fromEntries(voiceIds.map(id => [id,emptyVoice()])),loudestVoice:'',behavioralDriver:'',council:{voices:[],sharedAim:'',differentApproach:''},trialDrive:{option:'',action:'',reviewMoment:''},updatedAt:''};
  }
  function text(value,max=600){return typeof value==='string'?value.slice(0,max):''}
  function sanitize(raw) {
    const clean=emptyState(); if(!raw||raw.version!==1||typeof raw!=='object')return clean;
    clean.currentPhase=[...phaseOrder,'start'].includes(raw.currentPhase)?raw.currentPhase:'start';
    clean.voiceIndex=Math.max(0,Math.min(voiceIds.length-1,Number(raw.voiceIndex)||0));
    clean.situation={description:text(raw.situation?.description,700),dilemma:text(raw.situation?.dilemma,500),deadline:text(raw.situation?.deadline,80)};
    voiceIds.forEach(id=>{const item=raw.voices?.[id]||{};clean.voices[id]={visited:item.visited===true,recognized:item.recognized===true?true:item.recognized===false?false:null,response:text(item.response,500),responseOption:text(item.responseOption,180),other:text(item.other,180),protection:text(item.protection,120),influence:text(item.influence,120),currentPosition:POSITIONS[item.currentPosition]?item.currentPosition:'',trialPosition:POSITIONS[item.trialPosition]?item.trialPosition:''}});
    clean.loudestVoice=voiceIds.includes(raw.loudestVoice)?raw.loudestVoice:'';clean.behavioralDriver=voiceIds.includes(raw.behavioralDriver)?raw.behavioralDriver:'';
    clean.council={voices:Array.isArray(raw.council?.voices)?raw.council.voices.filter(id=>voiceIds.includes(id)).slice(0,2):[],sharedAim:text(raw.council?.sharedAim,350),differentApproach:text(raw.council?.differentApproach,350)};
    clean.trialDrive={option:text(raw.trialDrive?.option,180),action:text(raw.trialDrive?.action,500),reviewMoment:text(raw.trialDrive?.reviewMoment,180)};clean.updatedAt=text(raw.updatedAt,50);return clean;
  }
  function readState(){try{return sanitize(JSON.parse(localStorage.getItem(STORAGE_KEY)||'null'))}catch(_){return emptyState()}}
  let state=readState(); let saveTimer;
  function save(message='Rit lokaal bewaard.') {try{state.updatedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));document.querySelector('[data-storage-status]').textContent=message}catch(_){document.querySelector('[data-storage-status]').textContent='Lokale opslag is in deze browser niet beschikbaar.'}}
  function scheduleSave(){clearTimeout(saveTimer);document.querySelector('[data-storage-status]').textContent='Wordt lokaal bewaard…';saveTimer=setTimeout(()=>save(),180)}
  function hasLegacy(){try{const old=JSON.parse(localStorage.getItem(LEGACY_KEY)||'null');return old?.quizId==='wie-zit-aan-het-stuur'}catch(_){return false}}
  function elem(tag,className='',content=''){const node=document.createElement(tag);if(className)node.className=className;if(content)node.textContent=content;return node}
  function btn(label,className='',handler){const node=elem('button',className,label);node.type='button';node.addEventListener('click',handler);return node}
  function recognizedIds(){return voiceIds.filter(id=>state.voices[id].recognized===true)}
  function voiceColorClass(id){return `voice--${VOICES[id].colorToken}`}
  function voiceName(id){return VOICES[id]?.name||'Onbenoemde stem'}
  function phaseIndex(){return Math.max(0,phaseOrder.indexOf(state.currentPhase))}
  function announcePhase(){const root=document.querySelector('[data-route-progress]');const index=phaseIndex();root.hidden=state.currentPhase==='start';if(root.hidden)return;document.querySelector('[data-progress-label]').textContent=`Etappe ${index+1} van 7`;document.querySelector('[data-progress-title]').textContent=PHASES[state.currentPhase].title;document.querySelector('[data-progress-bar]').style.width=`${((index+1)/7)*100}%`;document.querySelector('[data-progress-steps]').replaceChildren(...phaseOrder.map((id,i)=>{const li=elem('li',i<index?'is-done':i===index?'is-current':'',String(i+1));li.setAttribute('aria-label',`${PHASES[id].title}${i===index?' — huidige etappe':''}`);return li}))}
  function shell(phase,kicker,title,copy){const root=elem('div','scene-shell');root.dataset.scene=phase;const transition=elem('div','transition-card');transition.append(elem('b','',PHASES[phase]?.title||'Start'),document.createTextNode(PHASES[phase]?.transition||''));const card=elem('section','scene-card scene-foreground');card.append(elem('p','scene-kicker',kicker),elem('h2','',title),elem('p','scene-copy',copy));if(phase!=='start')root.append(transition);root.append(card);return {root,card}}
  function actions(backLabel,nextLabel,onBack,onNext){const row=elem('div','scene-actions');if(onBack)row.append(btn(backLabel||'← Terug','',onBack));if(onNext)row.append(btn(nextLabel||'Verder →','primary',onNext));return row}
  function errorNode(){const p=elem('p','field-error');p.setAttribute('aria-live','polite');return p}
  function setPhase(id){state.currentPhase=id;if(id==='trial')recognizedIds().forEach(voiceId=>{if(!state.voices[voiceId].trialPosition)state.voices[voiceId].trialPosition=state.voices[voiceId].currentPosition});save();render();window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}
  function inputField(label,value,options={}){const wrap=elem('label');wrap.append(document.createTextNode(label));if(options.help)wrap.append(elem('small','',options.help));const field=document.createElement(options.single?'input':'textarea');if(!options.single){field.rows=options.rows||3}else field.type='text';field.value=value;field.maxLength=options.max||500;if(options.placeholder)field.placeholder=options.placeholder;field.addEventListener('input',()=>{options.onInput(field.value);scheduleSave()});wrap.append(field);return wrap}
  function radioGroup(legendText,name,options,value,onChange,className='choice-list'){const fieldset=elem('fieldset',className);fieldset.append(elem('legend','',legendText));options.forEach(option=>{const label=elem('label');const input=document.createElement('input');input.type='radio';input.name=name;input.value=option;input.checked=value===option;input.addEventListener('change',()=>{onChange(option);save();render()});label.append(input,document.createTextNode(option));fieldset.append(label)});return fieldset}

  function renderStart(){const {root,card}=shell('start','Keuze & innerlijk conflict','Wie zit er aan het stuur?','Zit je vast tussen verschillende reacties op één concrete situatie? Laat vier innerlijke stemmen afzonderlijk spreken, ontdek wat elke stem probeert te beschermen en geef ze een plaats in je auto. Na ongeveer 10–15 minuten kies je een kleine, voorlopige stap die meer dan één kant van jou meeneemt.');const meta=elem('ul','scene-meta');['10–15 minuten','Lokaal en privé','Geen diagnose of score'].forEach(x=>meta.append(elem('li','',x)));card.append(meta,elem('p','safety-note','Kies een situatie die ongemakkelijk maar momenteel hanteerbaar voelt. Dit spel geeft geen diagnose en beslist niet voor jou.'));const details=elem('details');details.innerHTML='<summary>Wanneer gebruik ik dit spel beter niet?</summary><p>Gebruik dit spel niet als enige hulp bij onmiddellijk gevaar, geweld, dwang, een acute crisis of gedachten aan zelfbeschadiging. Zoek dan steun bij iemand die je vertrouwt of bij professionele of acute hulp in je omgeving.</p>';card.append(details);if(hasLegacy())card.append(elem('p','legacy-note','Er staat nog een oudere Stuurtafelrit in deze browser. Die wordt niet automatisch geïnterpreteerd of verwijderd, omdat de nieuwe rit anders is opgebouwd.'));card.append(actions('',state.updatedAt?'Hervat mijn rit':'Begin de rit',null,()=>setPhase(state.currentPhase==='start'?'crossroads':state.currentPhase)));scene.replaceChildren(root)}

  function renderCrossroads(){const {root,card}=shell('crossroads','Etappe 1 van 7','Het kruispunt','Denk aan één concrete situatie waarin verschillende kanten van jou iets anders lijken te willen. Kies niet je hele leven tegelijk.');const inspiration=elem('details','inspiration');inspiration.innerHTML='<summary>Toon enkele mogelijke vertrekpunten</summary><ul><li>Ik wil iemand zeggen dat iets mij stoort.</li><li>Ik twijfel of ik op een uitnodiging inga.</li><li>Ik wil rust nemen, maar voel dat ik moet doorgaan.</li><li>Ik twijfel of ik opnieuw contact opneem.</li><li>Ik wil een kans aannemen, maar iets in mij remt af.</li></ul>';const fields=elem('div','field-stack');fields.append(inputField('Wat speelt er?',state.situation.description,{placeholder:'Beschrijf kort één concrete situatie.',max:700,onInput:v=>state.situation.description=v}),inputField('Tussen welke reacties of mogelijkheden twijfel je?',state.situation.dilemma,{placeholder:'Bijvoorbeeld: iets zeggen, zwijgen, wachten of afstand nemen.',max:500,onInput:v=>state.situation.dilemma=v}),radioGroup('Wanneer moet je ongeveer beslissen?','deadline',['Vandaag','Binnen enkele dagen','Later','Er is geen vaste deadline','Weet ik nog niet'],state.situation.deadline,v=>state.situation.deadline=v));const err=errorNode();card.append(inspiration,fields,err,actions('← Terug naar start','Laat de passagiers spreken →',()=>setPhase('start'),()=>{if(!state.situation.description.trim()||!state.situation.dilemma.trim()){err.textContent='Schrijf kort op wat er speelt en tussen welke reacties je twijfelt. Eén of twee zinnen per veld is genoeg.';(!state.situation.description.trim()?fields.querySelector('textarea'):fields.querySelectorAll('textarea')[1]).focus();return}state.voiceIndex=0;setPhase('voices')}));scene.replaceChildren(root)}

  function renderVoice(){const id=voiceIds[state.voiceIndex],voice=VOICES[id],answer=state.voices[id];const {root,card}=shell('voices',`Stem ${state.voiceIndex+1} van 4`,voice.name,voice.description);card.classList.add('voice-card',voiceColorClass(id));const heading=elem('div','voice-heading');heading.append(elem('span','voice-icon',voice.symbol));const copy=elem('div');copy.append(elem('span','voice-counter',`Stem ${state.voiceIndex+1} van 4`),elem('h2','',voice.name),elem('p','',voice.description));heading.replaceChildren(elem('span','voice-icon',voice.symbol),copy);card.querySelector('h2').remove();card.querySelector('.scene-copy').remove();card.append(heading);
    if(answer.recognized===false||answer.visited&&answer.recognized===null){card.append(elem('p','phase-note',answer.recognized===false?'Niet iedere stem hoeft in iedere situatie mee te rijden. Deze stem krijgt hier geen verplichte vervolgvragen.':'Je hoeft nu nog niet te weten of deze stem meerijdt. Onzekerheid blijft een geldig antwoord.'))}else{
      if(id==='relationRadar')card.append(inputField(voice.question,answer.other,{single:true,placeholder:'Een persoon, groep of relatie — of: ik weet het niet.',max:180,onInput:v=>{answer.other=v;answer.recognized=true;answer.visited=true}}));
      card.append(radioGroup(voice.question,`voice-${id}`,voice.options,answer.responseOption,v=>{answer.responseOption=v;answer.recognized=true;answer.visited=true}));
      if(id==='storyMaker')card.append(inputField('Maak minstens één gekozen zin af.',answer.response,{placeholder:voice.placeholder,max:500,onInput:v=>{answer.response=v;answer.recognized=true;answer.visited=true}}),radioGroup(voice.follow,`story-certainty`,['Iets wat ik rechtstreeks weet','Een vermoeden','Een vrees','Een hoop','Een combinatie hiervan','Ik weet het nog niet'],answer.other,v=>{answer.other=v;answer.recognized=true;answer.visited=true}));
      else card.append(inputField(voice.follow,answer.response,{placeholder:voice.placeholder,max:500,onInput:v=>{answer.response=v;answer.recognized=true;answer.visited=true}}));
      if(['reflex','compass'].includes(id)&&answer.responseOption==='Iets anders')card.append(inputField('Wat past beter?',answer.other,{single:true,max:180,onInput:v=>answer.other=v}));
      if(id==='compass')card.append(elem('p','phase-note','Een waarde is een richting, geen garantie op een bepaalde uitkomst.'));
    }
    const recognition=elem('div','recognition-actions');recognition.append(btn('Deze stem herken ik hier niet','',()=>{answer.visited=true;answer.recognized=false;answer.response='';answer.responseOption='';save();render()}),btn('Ik weet het nog niet','',()=>{answer.visited=true;answer.recognized=null;answer.response='';answer.responseOption='';save();render()}));recognition.children[0].setAttribute('aria-pressed',String(answer.recognized===false));recognition.children[1].setAttribute('aria-pressed',String(answer.visited&&answer.recognized===null));card.append(recognition);
    const err=errorNode();const isLast=state.voiceIndex===voiceIds.length-1;const transitionTexts=['De eerste reactie is gehoord. Nu kijken we naar wie er nog meer meereist.','Er is ook een relationeel perspectief gehoord. De volgende stem kijkt meer naar richting.','De richting is gehoord. Nu krijgt het verhaal van je hoofd een eigen plaats.','De vier stemmen hebben afzonderlijk gesproken. Nu bekijken we wat ze meebrengen.'];card.append(elem('p','voice-transition',transitionTexts[state.voiceIndex]),err,actions(state.voiceIndex?'← Vorige stem':'← Naar het kruispunt',isLast?'Bekijk wat ze meebrengen →':'Volgende stem →',()=>{if(state.voiceIndex){state.voiceIndex-=1;save();render()}else setPhase('crossroads')},()=>{if(!answer.visited){err.textContent='Kies wat het dichtst in de buurt komt, of geef aan dat je deze stem hier niet herkent of nog niet weet.';return}if(answer.recognized===true&&id==='storyMaker'&&!answer.response.trim()){err.textContent='Maak minstens één Verhalenmaker-zin af, of kies dat je deze stem hier niet herkent.';return}if(answer.recognized===true&&id!=='storyMaker'&&!answer.responseOption){err.textContent='Kies eerst welke reactie het dichtst in de buurt komt.';return}if(isLast)setPhase('cargo');else{state.voiceIndex+=1;save();render()}}));scene.replaceChildren(root)}

  function renderCargo(){const ids=recognizedIds();const {root,card}=shell('cargo','Etappe 3 van 7','Wat brengt iedere stem mee?','Alleen de stemmen die je herkende staan hier. Dit is geen tweede lange vragenlijst: twee korte keuzes per passagier.');const grid=elem('div','cargo-grid');if(!ids.length)grid.append(elem('p','phase-note','Je herkende voorlopig geen van de vier stemmen duidelijk. Dat hoeft niet geforceerd te worden; de rit kan verder met een open auto.'));ids.forEach(id=>{const voice=VOICES[id],answer=state.voices[id],item=elem('article',`cargo-card ${voiceColorClass(id)}`);const head=elem('header');head.append(elem('span','',voice.symbol),elem('strong','',voice.name));const fields=elem('div','cargo-fields');const protection=document.createElement('label');protection.textContent='Wat probeert deze stem vooral te beschermen of mogelijk te maken?';const pSelect=document.createElement('select');pSelect.append(new Option('Kies of weet ik nog niet',''));protections.forEach(x=>pSelect.append(new Option(x,x)));pSelect.value=answer.protection;pSelect.addEventListener('change',()=>{answer.protection=pSelect.value;save()});protection.append(pSelect);const influence=document.createElement('label');influence.textContent='Hoeveel invloed heeft deze stem momenteel op wat je werkelijk doet?';const iSelect=document.createElement('select');iSelect.append(new Option('Kies of weet ik nog niet',''));influences.forEach(x=>iSelect.append(new Option(x,x)));iSelect.value=answer.influence;iSelect.addEventListener('change',()=>{answer.influence=iSelect.value;save()});influence.append(iSelect);fields.append(protection,influence);item.append(head,fields);grid.append(item)});const err=errorNode();card.append(grid,elem('p','phase-note','Iedere stem kijkt door één raam. Geen enkel raam toont de hele weg.'),err,actions('← Naar de stemmen','Bouw mijn huidige auto →',()=>{state.voiceIndex=voiceIds.length-1;setPhase('voices')},()=>{const missing=ids.find(id=>!state.voices[id].protection||!state.voices[id].influence);if(missing){err.textContent=`Kies bij ${voiceName(missing)} nog wat de stem beschermt en hoeveel invloed ze heeft. “Weet ik nog niet” is geldig.`;return}setPhase('positions')}));scene.replaceChildren(root)}

  function positionsObject(key){return Object.fromEntries(recognizedIds().map(id=>[id,state.voices[id][key]]))}
  function renderCarLayout({positions,mode,title}){const car=elem('section','car-layout');car.dataset.carMode=mode;const head=elem('div','car-layout__label');head.append(elem('strong','',title),elem('span','',mode==='trial'?'Tijdelijke opstelling':'Huidige bezetting'));const cabin=elem('div','car-layout__cabin');Object.values(POSITIONS).forEach(position=>{const zone=elem('section','seat-zone');zone.dataset.seat=position.id;zone.append(elem('h4','',position.name),elem('p','',position.help));const voices=elem('div','seat-zone__voices');const occupants=voiceIds.filter(id=>positions[id]===position.id);if(!occupants.length)voices.append(elem('span','seat-empty','Niemand geplaatst'));occupants.forEach(id=>{const token=elem('span',`voice-token ${voiceColorClass(id)}`);token.dataset.voice=id;token.append(elem('i','voice-token__icon',VOICES[id].symbol),document.createTextNode(VOICES[id].shortName));voices.append(token)});zone.append(voices);cabin.append(zone)});car.append(head,cabin);return car}
  function positionControls(key,onUpdate){const grid=elem('div','position-grid');recognizedIds().forEach(id=>{const row=elem('div',`position-row ${voiceColorClass(id)}`);row.append(elem('strong','',voiceName(id)));const choices=elem('div');Object.values(POSITIONS).forEach(position=>{const control=btn(position.name,'',()=>{state.voices[id][key]=position.id;save();onUpdate()});control.setAttribute('aria-pressed',String(state.voices[id][key]===position.id));choices.append(control)});row.append(choices);grid.append(row)});return grid}

  function voiceRadioQuestion(legendText,name,value,onChange){const ids=recognizedIds();return radioGroup(legendText,name,ids.map(voiceName),value?voiceName(value):'',label=>onChange(ids.find(id=>voiceName(id)===label)||''))}
  function renderPositions(){const ids=recognizedIds();const {root,card}=shell('positions','Etappe 4 van 7','Wie zit waar?','Plaats de stemmen zoals het nu werkelijk voelt, niet zoals je vindt dat het zou moeten zijn. Meerdere stemmen mogen dezelfde plek krijgen en niemand hoeft aan het stuur te staan.');const carHolder=elem('div');const controlsHolder=elem('div');const update=()=>{carHolder.replaceChildren(renderCarLayout({positions:positionsObject('currentPosition'),mode:'current',title:'Mijn auto nu'}));controlsHolder.replaceChildren(positionControls('currentPosition',update));renderDriverQuestions()};const driverHolder=elem('div','driver-questions');const feedback=elem('p','driver-feedback');function renderDriverQuestions(){driverHolder.replaceChildren();if(!ids.length){feedback.textContent='Er is nog geen herkende stem om als luidste of gedragsbepalende stem te kiezen.';return}driverHolder.append(voiceRadioQuestion('Welke stem praat het luidst in je hoofd?','loudest',state.loudestVoice,id=>{state.loudestVoice=id;save();renderPositions()}),voiceRadioQuestion('Welke stem bepaalt uiteindelijk het vaakst wat je werkelijk doet?','behavior-driver',state.behavioralDriver,id=>{state.behavioralDriver=id;save();renderPositions()}));feedback.textContent=state.loudestVoice&&state.behavioralDriver?(state.loudestVoice===state.behavioralDriver?'Deze stem klinkt momenteel luid én heeft veel invloed. Dat betekent niet automatisch dat ze gelijk of ongelijk heeft.':'De luidste stem hoeft niet dezelfde te zijn als de stem die je gedrag bepaalt.'):'Kies beide alleen volgens hoe deze situatie nu werkelijk voelt.'}
    update();renderDriverQuestions();const err=errorNode();card.append(carHolder,elem('p','phase-note','Aan het stuur gaat over huidige invloed, niet over waarheid of waarde.'),controlsHolder,driverHolder,feedback,err,actions('← Wat ze meebrengen',ids.length<2?'Kies een testrit →':'Roep de Binnenraad samen →',()=>setPhase('cargo'),()=>{const missing=ids.find(id=>!state.voices[id].currentPosition);if(missing){err.textContent=`Geef ${voiceName(missing)} nog een huidige plaats. Buiten de auto is ook een geldige positie.`;return}if(ids.length&&(!state.loudestVoice||!state.behavioralDriver)){err.textContent='Kies nog welke stem het luidst praat en welke stem je gedrag het vaakst bepaalt.';return}setPhase(ids.length<2?'trial':'council')}));scene.replaceChildren(root)}

  function renderCouncil(){const ids=recognizedIds();if(ids.length<2){setPhase('trial');return}const {root,card}=shell('council','Etappe 5 van 7','De Binnenraad','Welke twee stemmen lijken in deze situatie het meest aan een andere richting te trekken?');const pair=elem('fieldset','council-pair');pair.append(elem('legend','visually-hidden','Kies precies twee stemmen'));ids.forEach(id=>{const label=elem('label',voiceColorClass(id));const input=document.createElement('input');input.type='checkbox';input.checked=state.council.voices.includes(id);input.addEventListener('change',()=>{if(input.checked&&state.council.voices.length<2)state.council.voices.push(id);else if(!input.checked)state.council.voices=state.council.voices.filter(x=>x!==id);else input.checked=false;save();renderCouncil()});label.append(input,document.createTextNode(`${VOICES[id].symbol} ${voiceName(id)}`));pair.append(label)});card.append(pair);if(state.council.voices.length===2){const fields=elem('div','field-stack');fields.append(inputField('Ze willen misschien allebei …',state.council.sharedAim.startsWith('__')?'':state.council.sharedAim,{single:true,max:350,onInput:v=>state.council.sharedAim=v}),inputField('Maar ze verschillen over …',state.council.differentApproach.startsWith('__')?'':state.council.differentApproach,{single:true,max:350,onInput:v=>state.council.differentApproach=v}));const unknown=elem('div','recognition-actions');unknown.append(btn('Ik zie nog geen overeenkomst','',()=>{state.council.sharedAim='__none__';save();renderCouncil()}),btn('Ik weet het nog niet','',()=>{state.council.sharedAim='__unknown__';save();renderCouncil()}),btn('Verschil nog onduidelijk','',()=>{state.council.differentApproach='__unknown__';save();renderCouncil()}));card.append(fields,unknown);if(state.council.sharedAim&&!state.council.sharedAim.startsWith('__')&&state.council.differentApproach&&!state.council.differentApproach.startsWith('__'))card.append(elem('p','council-summary',`${voiceName(state.council.voices[0])} en ${voiceName(state.council.voices[1])} willen misschien allebei ${state.council.sharedAim}, maar verschillen over ${state.council.differentApproach}.`))}
    const err=errorNode();card.append(elem('p','phase-note','Twee stemmen kunnen hetzelfde doel hebben en toch een heel andere aanpak voorstellen.'),err,actions('← Naar mijn auto','Kies een testrit →',()=>setPhase('positions'),()=>{if(state.council.voices.length!==2){err.textContent='Kies twee stemmen die het meest aan een andere richting trekken.';return}if(!state.council.sharedAim||!state.council.differentApproach){err.textContent='Vul het mogelijke gedeelde doel en verschil in, of kies dat je het nog niet ziet.';return}setPhase('trial')}));scene.replaceChildren(root)}

  function renderTrial(){const {root,card}=shell('trial','Etappe 6 van 7','De testrit','Kies geen definitieve levensbeslissing. Wat is een kleine stap voor de eerstvolgende kilometer?');card.append(radioGroup('Welke kleine stap kun je proberen zonder meteen de hele situatie op te lossen?','trial-option',trialOptions,state.trialDrive.option,v=>state.trialDrive.option=v),inputField('Omschrijf de stap kort in je eigen woorden.',state.trialDrive.action,{placeholder:'Bijvoorbeeld: ik vraag eerst wat die persoon precies bedoelde.',max:500,onInput:v=>state.trialDrive.action=v}),radioGroup('Wanneer wil je opnieuw bekijken of deze stap nog klopt?','review-moment',reviewOptions,state.trialDrive.reviewMoment,v=>state.trialDrive.reviewMoment=v));const cars=elem('div','trial-cars');cars.append(renderCarLayout({positions:positionsObject('currentPosition'),mode:'current',title:'Mijn auto nu'}),renderCarLayout({positions:positionsObject('trialPosition'),mode:'trial',title:'Mijn auto voor de testrit'}));const controls=elem('div','trial-controls');const rerender=()=>renderTrial();controls.append(elem('p','phase-note','Alleen voor deze kleine testrit: geef één of meer stemmen eventueel een andere plaats. Je hoeft geen stem uit de auto te gooien.'),positionControls('trialPosition',rerender));const err=errorNode();card.append(cars,controls,err,actions('← Naar de Binnenraad','Bekijk mijn ritverslag →',()=>setPhase(recognizedIds().length<2?'positions':'council'),()=>{if(!state.trialDrive.option){err.textContent='Kies een kleine stap — “Ik weet het nog niet” is ook geldig.';return}const missing=recognizedIds().find(id=>!state.voices[id].trialPosition);if(missing){err.textContent=`Geef ${voiceName(missing)} nog een tijdelijke plaats voor de testrit.`;return}setPhase('report')}));scene.replaceChildren(root)}

  function definitionList(rows){const dl=elem('dl');rows.filter(([,v])=>v&&String(v).trim()).forEach(([label,value])=>{const wrap=elem('div'),dt=elem('dt','',label),dd=elem('dd','',String(value));wrap.append(dt,dd);dl.append(wrap)});return dl}
  function responseFor(id){const v=state.voices[id];if(v.recognized===false)return'Deze stem speelde in deze situatie geen duidelijke rol.';if(v.recognized===null)return'Je wist nog niet of deze stem meereed.';return [v.responseOption,v.other,v.response].filter(Boolean).join(' · ')}
  function renderReport(){const {root,card}=shell('report','Etappe 7 van 7','Het ritverslag','Geen score, diagnose of persoonlijkheidsprofiel. Alleen een vaste weergave van wat je in deze situatie zelf invulde.');card.classList.add('report');const crossing=elem('section','report-section');crossing.append(elem('span','','1 · Jouw kruispunt'),elem('h3','','Waar deze rit begon'),definitionList([['Wat er speelt',state.situation.description],['Tussen welke reacties',state.situation.dilemma],['Mogelijke deadline',state.situation.deadline||'Niet ingevuld']]));const voicesSection=elem('section','report-section');voicesSection.append(elem('span','','2 · Wat de stemmen zeiden'),elem('h3','','Vier tijdelijke perspectieven'));const voiceGrid=elem('div','report-voices');voiceIds.forEach(id=>{const v=state.voices[id],article=elem('article',`report-voice ${voiceColorClass(id)}`);article.append(elem('strong','',`${VOICES[id].symbol} ${voiceName(id)}`),elem('p','',responseFor(id)));if(v.recognized===true)article.append(elem('small','',`${v.protection||'Bescherming onbekend'} · ${v.influence||'Invloed onbekend'} · ${POSITIONS[v.currentPosition]?.name||'Geen plaats'}`));voiceGrid.append(article)});voicesSection.append(voiceGrid);const volume=elem('section','report-section');volume.append(elem('span','','3 · Volume en invloed'),elem('h3','','Wie klonk luid en wie bepaalde gedrag?'),definitionList([['Luidste stem',state.loudestVoice?voiceName(state.loudestVoice):'Niet gekozen'],['Feitelijke bestuurder',state.behavioralDriver?voiceName(state.behavioralDriver):'Niet gekozen']]));if(state.loudestVoice&&state.behavioralDriver)volume.append(elem('p','driver-feedback',state.loudestVoice===state.behavioralDriver?'Deze stem klinkt momenteel luid én heeft veel invloed. Dat betekent niet automatisch dat ze gelijk of ongelijk heeft.':'De luidste stem hoeft niet dezelfde te zijn als de stem die je gedrag bepaalt.'));
    const council=elem('section','report-section');council.append(elem('span','','4 · De Binnenraad'),elem('h3','','Waar twee stemmen elkaar ontmoetten'));if(state.council.voices.length<2)council.append(elem('p','',recognizedIds().length<2?'Minder dan twee stemmen werden herkend; deze ontmoeting werd overgeslagen.':'Er werden geen twee stemmen gekozen.'));else if(state.council.sharedAim==='__none__')council.append(elem('p','','Je zag voorlopig nog geen duidelijk gedeeld doel. Dat hoeft niet geforceerd te worden.'));else if(state.council.sharedAim==='__unknown__')council.append(elem('p','','Het mogelijke gedeelde doel bleef nog open.'));else council.append(elem('p','council-summary',`${voiceName(state.council.voices[0])} en ${voiceName(state.council.voices[1])} willen misschien allebei ${state.council.sharedAim}, maar verschillen over ${state.council.differentApproach==='__unknown__'?'een aanpak die nog niet duidelijk is':state.council.differentApproach}.`));
    const cars=elem('section','report-section');cars.append(elem('span','','5 · Twee auto’s'),elem('h3','','Huidig en tijdelijk naast elkaar'));const comparison=elem('div','result-car-comparison');comparison.dataset.resultCarComparison='';comparison.append(renderCarLayout({positions:positionsObject('currentPosition'),mode:'current',title:'Mijn auto nu'}),renderCarLayout({positions:positionsObject('trialPosition'),mode:'trial',title:'Mijn auto voor de testrit'}));cars.append(comparison);const kilometer=elem('section','report-section');kilometer.append(elem('span','','6 · De eerstvolgende kilometer'),elem('h3','','Een voorlopige testrit'),definitionList([['Gekozen richting',state.trialDrive.option],['In eigen woorden',state.trialDrive.action||'Niet verder omschreven'],['Opnieuw bekijken',state.trialDrive.reviewMoment||'Geen moment gekozen']]));card.append(crossing,voicesSection,volume,council,cars,kilometer,elem('p','report-boundary','Je hoeft niet te bepalen welke stem voor altijd gelijk heeft. Deze opstelling geldt alleen voor deze situatie en deze eerstvolgende stap.'));
    const row=elem('div','scene-actions');row.append(btn('Antwoorden aanpassen','',()=>setPhase('crossroads')),btn('Rit opnieuw bekijken','',()=>{card.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});card.focus?.()}),btn('Nieuw kruispunt','',()=>{if(!confirm('Wil je deze rit vervangen door een nieuw kruispunt? Alleen de gegevens van dit autospel worden gewist.'))return;localStorage.removeItem(STORAGE_KEY);state=emptyState();render()}),btn('Mijn gegevens voor dit spel verwijderen','danger',()=>{if(!confirm('Wil je alleen de lokale gegevens van “Wie zit er aan het stuur?” verwijderen?'))return;localStorage.removeItem(STORAGE_KEY);state=emptyState();document.querySelector('[data-storage-status]').textContent='De lokale gegevens van dit autospel zijn verwijderd.';render()}));card.append(row);scene.replaceChildren(root)}

  function render(){announcePhase();if(state.currentPhase==='start')renderStart();else if(state.currentPhase==='crossroads')renderCrossroads();else if(state.currentPhase==='voices')renderVoice();else if(state.currentPhase==='cargo')renderCargo();else if(state.currentPhase==='positions')renderPositions();else if(state.currentPhase==='council')renderCouncil();else if(state.currentPhase==='trial')renderTrial();else renderReport()}
  window.ONWIJZE_STEERING_MVP={VOICES,POSITIONS,PHASES,renderCarLayout};
  render();
}());
